ebi-uniprot/uniprot-website

package.json, src/results/ResultsContainer.tsx, src/results/__tests__/__snapshots__/ResultsTable.spec.tsx.snap, src/search/state/actions.ts, src/state/reducers.ts, yarn.lock
Reset the query (actually the whole state at the moment) when the user navigates away from the results page (unmount)
=> Add root reducer to reset state when results component is unmounted

src/components/AutocompleteWrapper.tsx, src/search/Field.tsx
Fields with a suggester API should display options in `Value [ID]` format and also use the same format once selected.
=> Trm 21704 autocomplete show id in options (MERGE THIS ONE SECOND PLZ)

src/results/ResultsContainer.tsx, src/search/SearchContainer.tsx
This solves the issue with back button from the entry page back to results. The issue was to do with the lifecycle of the components, and the fact the url was parsed and updated in a Search component rather than Results component.
=> Move url update from Search to Results

src/entry/Entry.tsx, src/model/Induction.tsx, src/model/TissueSpeficity.tsx, src/model/__tests__/Induction.tsx, src/model/__tests__/TissueSpeficity.tsx, src/model/__tests__/__snapshots__/Induction.tsx.snap, src/model/__tests__/__snapshots__/TissueSpeficity.tsx.snap
Create an Expression section on the entry view consisting of two simple components:
* TissueSpeficity
* Induction
Test coverage is low because `modelData.json` is missing TissueSpeficity and Induction comment types. Creating a separate Jira to update this file as it is maintained by backend and we want to keep in sync with their test files.
=> Entry expression trm 21672

package.json, src/components/__tests__/UniProtEvidenceTag.spec.tsx, src/components/__tests__/__snapshots__/UniProtEvidenceTag.spec.tsx.snap, src/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/model/uniprotkb/ProteinNamesConverter.ts, src/results/state/resultsActions.ts, src/view/uniprotkb/components/AnnotationScoreDoughnutChart.tsx, src/view/uniprotkb/components/ProteinOverviewView.tsx, src/view/uniprotkb/components/SequenceView.tsx, src/view/uniprotkb/components/UniProtCard.tsx, src/view/uniprotkb/components/__tests__/AnnotationScoreDoughnutChart.spec.tsx, src/view/uniprotkb/components/__tests__/ProteinOverview.spec.tsx, src/view/uniprotkb/components/__tests__/__snapshots__/AnnotationScoreDoughnutChart.spec.tsx.snap, src/view/uniprotkb/components/__tests__/__snapshots__/ProteinOverview.spec.tsx.snap, src/view/uniprotkb/components/__tests__/__snapshots__/UniProtCard.spec.tsx.snap, src/view/uniprotkb/components/styles/UniProtCard.scss, src/view/uniprotkb/summary/__tests__/__snapshots__/ProteinSummary.spec.tsx.snap
- This needs this Franklin PR https://github.com/ebi-uniprot/franklin-sites/pull/43 to be merged first as there is an error about `div`s being children of `p`s.
- Provided two different IDs to UniProtEvidenceTag to avoid encountering 'two children with the same key' warning during tests.
https://www.ebi.ac.uk/panda/jira/browse/TRM-22818
100%
In results and protein summary
N/A
N/A
=> Trm 22818/annotation score visualisation

src/entry/Entry.tsx
[TRM-22525](https://www.ebi.ac.uk/panda/jira/browse/TRM-22525)
*Was not needed.*
*This only prevents re-rendering of the page. At the moment there are a few console logs -- from other pieces of code, when the page or `Entry` component renders. If you clean the console and click on the in-page navigation links, you should not those console logs to re-appear. This is the simplest way to visually verify this PR is working.*
*No.*
*No.*
=> fixes the re-rendering issue with the in-page navigation

src/__mockData__/database.ts, src/data/database.ts, src/data/databaseInfo.json, src/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/entry/__tests__/__snapshots__/EntryExternalLinks.spec.tsx.snap, src/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/model/utils/XrefUtils.tsx, src/view/uniprotkb/components/XRefView.tsx
* Fix HUGE, ROUGE, and GenAtlas implicit links
* Prevent properties being displayed if xref is implicit
=> Implicit xref fix

src/model/ColumnConfiguration.tsx, src/utils/externalUrls.ts, src/view/uniprotkb/components/GOView.tsx, src/view/uniprotkb/components/OrganismView.tsx, src/view/uniprotkb/components/SequenceView.tsx
* https://www.ebi.ac.uk/panda/jira/browse/TRM-23392
* In addition, to this jira I made a small modification to the sequence caution key of prefixing with `sequenceCautionType` as when I was testing I saw in at Q9Y263 that the sequence AAD42075.1 differs for two reasons and so was giving a react duplicate key warning.
Didn't write additional tests as this basically adding lines to a config file.
* QuickGO link: Add the the QuickGO columns
* NCBI: Organism names > Taxonomic identifier
* ENA: anywhere there is a sequence caution eg Q9Y263
No
N/A
=> External links trm 23392

src/hooks/__tests__/useLocalStorage.spec.ts, src/hooks/useLocalStorage.ts
added a new custom hook to access localStorage through react hooks logic like this:
```js
const [value, setValue, deleteValue] = useLocalStorage('key', 'default value');
```
It will *eventually* persist to localStorage. `value` is updated right away though.
This should be usable the same way than react's `useState` (compatible API).
One limitation is that values need to be JSON-serialisable.
As localStorage and JSON.parse and JSON.stringify are blocking operation, we try to execute as much of it as we can whenever the browser has time to do so through `requestIdleCallback`.
=> useLocalStorage

src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/FeaturesTableView.tsx, src/uniprotkb/components/protein-data-views/FeaturesView.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/FeaturesView.spec.tsx.snap
This is a (yet to be created) subtask of https://www.ebi.ac.uk/panda/jira/browse/TRM-24238
There's been requests (on the covid platform) to show the sequence in some form as part of the `protvista-datatable`. This PR offers a simple solution "for now" while we decide how we want to integrate the rest of requirements, and has been discussed with @SangyaP 
Will cherry-pick the PR on covid-19 when approved.
=> Add scroll to view, add sequence to table

.eslintrc, package.json, src/shared/components/error-component/__tests__/__snapshots__/ErrorComponent.spec.tsx.snap, src/shared/components/error-pages/__tests__/__snapshots__/JobErrorPage.spec.tsx.snap, src/shared/components/error-pages/__tests__/__snapshots__/ResourceNotFoundPage.spec.tsx.snap, src/shared/components/error-pages/__tests__/__snapshots__/ServiceUnavailablePage.spec.tsx.snap, src/tools/align/components/AlignForm.tsx, src/tools/blast/components/BlastForm.tsx, src/tools/blast/components/__tests__/__snapshots__/BlastForm.spec.tsx.snap, src/tools/blast/components/results/BlastResultTaxonomy.tsx, src/tools/blast/types/apiSequenceData.ts, src/tools/components/SequenceSearchLoader.tsx, src/tools/components/__tests__/SequenceSearchLoader.spec.tsx, src/tools/dashboard/components/Row.tsx, src/tools/styles/ToolsForm.scss, src/uniparc/config/apiUrls.ts, src/uniprotkb/__mocks__/entryModelData.json, src/uniprotkb/adapters/__tests__/__snapshots__/entryToFASTAWithHeaders.spec.ts.snap, src/uniprotkb/adapters/entryToFASTAWithHeaders.ts, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryPublications.spec.tsx.snap, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/UniProtKBEntryPublications.spec.tsx.snap, src/uniprotkb/components/results/__tests__/__snapshots__/UniProtKBCard.spec.tsx.snap, src/uniprotkb/config/__tests__/__snapshots__/ColumnConfiguration.spec.tsx.snap, yarn.lock
Group of changes mainly aimed at handling better multiple sequences FASTAs
See [corresponding PR](https://github.com/ebi-uniprot/franklin-sites/pull/97) in franklin-sites
- Add ProcessedSequence object state to the forms to handle validation, name extraction, and prepending of new sequences
- Seems a bit redundant with the `sequence` state holding the raw sequence text and the form input config though
- Better handling of job name autofill
- If user modifies, don't autofill anymore
- use NCBI identifier extracted from FASTA header of available
- use '<first found identifier> + 2' in case of 3 sequences
- use '3 sequences' if no identifier found
- Auto load from accession or identifier
- in case of align form:
- prepend new sequence to already provided ones
- handle pasting of multiple …
=> Handle multiple fasta

package.json, src/shared/utils/__tests__/utils.spec.ts, src/shared/utils/utils.ts, src/tools/blast/components/results/BlastResult.tsx, src/tools/blast/components/results/BlastResultHitDistribution.tsx, src/tools/blast/components/results/BlastResultLocalFacets.tsx, src/tools/blast/components/styles/BlastResultHitDistribution.scss, yarn.lock
- Modify Histogram filters to use an automatically calculated number of bins depending on number of items in original dataset (number of hsp across all hits)
- Modify hit distribution tab:
- Connect to filtered data
- Display all value types
- Let user change number of bins (defaults to auto)
=> use automatic bin size, connect hit distribution page to facet filters

src/tools/align/components/AlignForm.tsx, src/tools/blast/components/BlastForm.tsx, src/tools/blast/components/__tests__/__snapshots__/BlastForm.spec.tsx.snap, src/tools/dashboard/components/Row.tsx, src/tools/dashboard/components/styles/Dashboard.scss, src/tools/styles/ToolsForm.scss
Change Dashboard style to:
- avoid having the action buttons escape when the screen starts to get narrower
- give more space to the title
- related to that, made title monospace on Align and BLAST forms to dinamically set the needed width for the input (no way to style an input[type="text"] relative to the size of its content 🤷🏽‍♂️)
- implement the alternative grid for small screens according to mockup
=> make responsive dashboard, avoid action buttons escaping

.gitignore, src/tools/align/components/results/AlignResult.tsx, src/tools/align/components/results/AlignResultOverview.tsx, src/tools/align/components/results/styles/AlignLabel.scss, src/tools/align/components/results/styles/AlignResultOverview.scss, src/tools/align/components/results/styles/PhyloTree.scss, src/tools/align/utils/useSequenceInfo.ts, src/tools/blast/components/results/__tests__/HSPDetailPanel.spec.tsx, src/tools/blast/utils/__tests__/hsp.spec.ts, src/tools/components/MSAView.tsx
- Added MSAWrapper to Align overview
- Changed data enrichment on Align pages to use accessions endpoint instead of features endpoint
- Used labels _outside_ of MSAWrapper (will see later what we do about it)
but
- 😕 generates a lot of warnings, I think related to the overview bit
- Somehow it loaded at some point (looked nice by the way), but most of the time it doesn't: race-condition of some sort?
UPDATE: Actually, if you browse to a tab, and then back to Overview tab, then the overview bit of the visualisation, and the annotation bit both work
=> Align overview

babel.config.js, package.json, setupJest.js, src/shared/hooks/useCustomElement.ts, src/shared/utils/utils.ts, src/tools/blast/components/results/BlastResultTable.tsx, src/tools/blast/components/results/__tests__/BlastResultTable.spec.tsx, src/tools/components/AlignmentOverview.tsx, src/tools/components/MSAView.tsx, src/tools/components/MSAWrappedView.tsx, src/uniprotkb/components/entry/FeatureViewer.tsx, src/uniprotkb/components/entry/InteractionSection.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/CatalyticActivityView.tsx, src/uniprotkb/components/protein-data-views/FeaturesTableView.tsx, src/uniprotkb/components/protein-data-views/FeaturesView.tsx, src/uniprotkb/components/protein-data-views/PDBView.tsx, src/uniprotkb/components/protein-data-views/VariationView.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/CatalyticActivityView.spec.tsx.snap, yarn.lock
Handle issues seen during user testing where some error would make whole chunks of the website (even seemingly unrelated to where the error is) fail to the user. Those errors would be due to compatibility issues
- Dynamically load rhea component (uses webcomponent, and auto declares it to the customElementRegistry):
- Now, if something fails (most likely, web components not supported) -> just show the reaction, but no visuals
- Change the way the custom elements are defined and registered. Now uses custom hook, and have a returned flag when the components are indeed defined, which gives us:
- Errors contained
- Only load custom element logic on render
- Better handling of race conditions through the returned flag (wait for definition before doing something)
- Tweak the config of …
=> 2020 11 uniref  better compat

src/tools/align/components/results/AlignLabel.tsx, src/tools/align/components/results/AlignResult.tsx, src/tools/align/components/results/AlignResultOverview.tsx, src/tools/align/components/results/AlignResultPIM.tsx, src/tools/align/components/results/AlignResultPhyloTree.tsx, src/tools/align/components/results/PhyloTree.tsx, src/tools/align/components/results/styles/AlignLabel.scss, src/tools/blast/components/results/HSPDetailPanel.tsx, src/tools/blast/components/results/__tests__/HSPDetailPanel.spec.tsx, src/tools/blast/components/results/__tests__/__snapshots__/HSPDetailPanel.spec.tsx.snap, src/tools/components/AlignmentView.tsx, src/tools/components/Overview.tsx, src/tools/components/Wrapped.tsx, src/tools/components/styles/alignment-view.scss
PR inside the PR
handles:
- connect align label checkboxes to blast and align action buttons
- add checkboxes and connect to action buttons in phylotree ad pim components
- in wrapped view, toggle all checkboxes corresponding to the same sequence
- floor the coordinate number that was appearing as a decimal when first switching to overview
- make whole align label clickable as way to select one of the alignments
- optimise use of grid and cell positionning
- push the cells to the bottom to keep alignment without injecting dynamic style depending on track information
- merge "rows" into one big section and handle grids as grids (stuff all the cells in one grid, and assign areas to those cells)
- define size of side columns depending on content and not based on fixed sizing anymore -> …
=> MSA PR in the PR

__mocks__/protvista-variation-adapter.js, package.json, src/uniprotkb/components/protein-data-views/FeaturesTableView.tsx, src/uniprotkb/components/protein-data-views/VariationView.tsx, src/uniprotkb/components/protein-data-views/__tests__/VariationView.spec.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/VariationView.spec.tsx.snap, yarn.lock
Noticed an issue where clicking on a variant (dot) in the viewer wouldn't highlight it in the table. This is because both components need to use "transformedData" which has `protvistaFeatureId` set.
Fixed and updated tests.
=> Fix issue with variant highlight

src/tools/align/components/results/AlignResultOverview.tsx, src/tools/components/Overview.tsx
A few bug fixes for align:
1. When a user provides a sequence that isn't in UniProtKB we now set `from`, `to`, `length`. Without these we were getting some negative value errors in protvista's SVGs.
2. Don't set `initialDisplayEnd` if `displayEnd` is already defined as this was causing the navigation to alternate between `initialDisplayEnd` and `displayEnd` during scrolling.
=> 2020 12 a few alignment fixes

src/app/components/styles/app.scss, src/tools/blast/components/results/__tests__/__snapshots__/HSPDetailPanel.spec.tsx.snap, src/tools/components/AlignmentView.tsx, src/tools/components/Wrapped.tsx, src/tools/components/styles/alignment-view.scss, src/tools/config/msaColorSchemes.ts
Not as simple as expected:
Had to de-optimise the staggered rendering in wrapped view as the conservation highlight was disappearing when lower instances get added and the numbers on the right get longer and so push the grid's middle column to be smaller without the component detecting that it got resized. So, one way to solve that was to render everything in one go.
As an other way to optimise the page, I applied [this approach](https://web.dev/content-visibility/) to the MSA viewer as the space for the MSA viewer will be fixed once all the elements are rendered once.
=> switch default highlight to conservation

src/uniprotkb/adapters/functionConverter.ts, src/uniprotkb/components/entry/FunctionSection.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
During Preethi’s presentation, I noticed we were missing a comment type in the new website: Caution.
See https://www.uniprot.org/uniprot/P14210#miscellaneous for an example. As it’s highlighted in the old website, I take it it has to be highlighted for the user too so thought of using a message component of status “warning”.
=> Add caution comment

src/uniprotkb/adapters/uniProtkbConverter.ts, src/uniprotkb/components/entry/Entry.tsx, src/uniprotkb/utils/index.ts
Noticed that obsolete entries were displaying an error page instead of the obsolete page
The issue was to do with the fact the model for obsolete entries was separate from the one used for the transformed data and therefore the `entryType` wasn't converted to an enum as it should have been. I've simplified the type definition by adding `inactiveReason` as an optional attribute to the main model so that it can run through the converter. As a result the entry type is now identified correctly and the relevant page displayed (B9U1N9 for instance).
No new tests added or updated.
=> 2020 14 uniparc results inactive

src/app/components/HomePage.tsx, src/app/components/HomePageNonCritical.tsx, src/app/components/__tests__/HomePage.spec.tsx, src/app/components/__tests__/__snapshots__/HomePage.spec.tsx.snap, src/app/config/urls.ts, src/shared/components/layouts/UniProtHeader.tsx, src/shared/config/InfoMappings.tsx, src/tools/adapters/parameters.ts, src/tools/components/ResultDownload.tsx, src/tools/config/urls.ts, src/tools/dashboard/components/Dashboard.tsx, src/tools/types/toolsFormParameters.ts, src/tools/types/toolsJob.ts, src/tools/types/toolsJobTypes.ts, src/tools/types/toolsServerParameters.ts, src/tools/utils/isValidServerID.ts, src/uniprotkb/components/search/SearchContainer.tsx, src/uniprotkb/components/search/__tests__/SearchContainer.spec.tsx, src/uniprotkb/components/search/__tests__/__snapshots__/SearchContainer.spec.tsx.snap, src/uniprotkb/components/search/styles/search-container.scss
Add search examples, upload lists link and update list of examples and search input header sentence when the namespace selector is used on the homepage.
Hoisted the namespace state hook to the parent component so that the header sentence can be updated after selection. Added buttons to add examples to the search box but the behaviour of this is TBC.
- Update snapshots
- Add a test for namespace selection
- Add a test for example selection
=> Add logic for examples and text

package.json, src/app/components/App.tsx, src/app/config/urls.ts, src/query-builder/components/QueryBuilder.tsx, src/query-builder/components/__tests__/QueryBuilder.spec.tsx, src/query-builder/components/__tests__/__snapshots__/QueryBuilder.spec.tsx.snap, src/query-builder/components/styles/query-builder.scss, src/shared/__test-helpers__/RenderWithRedux.tsx, src/shared/components/download/Download.tsx, src/shared/components/layouts/UniProtHeader.tsx, src/shared/components/results/ResultsButtons.tsx, src/tools/components/ResultButtons.tsx, yarn.lock
Put the query builder in a side panel. See [TRM-25301](https://www.ebi.ac.uk/panda/jira/browse/TRM-25301).
Remove location for query builder, initialise given the current namespace or UniProtKB by default
Updated existing test snapshots
=> 2020 15 side panel query builder

src/shared/components/layouts/SlidingPanel.tsx, src/shared/components/layouts/UniProtHeader.tsx, src/shared/components/layouts/__tests__/SlidingPanel.spec.tsx, src/shared/components/results/ResultsButtons.tsx, src/tools/blast/components/results/HSPDetailPanel.tsx, src/tools/components/ResultButtons.tsx
[Close sliding panel when user clicks outside.](https://www.ebi.ac.uk/panda/jira/browse/TRM-25265)
* Inside of SlidingPanel added a listener to the body for mouse down events and calls the prop onClickOutside if the target is outside.
* Updated instances of SlidingPanel in the codebase to use this behaviour.
* Click outside of the component
* Click inside of the component
=> 2020 15 side panel click outside

src/shared/components/results/ResultsView.tsx, src/shared/components/results/__tests__/ResultsContainer.spec.tsx, src/shared/hooks/__tests__/useLocalStorage.spec.ts, src/shared/hooks/useLocalStorage.ts
Fix different issues when, in a search page, switching the namespace and doing a new search
Fix `useLocalStorage` to change the returned value when the key is changed
Updated existing tests and added new test for `useLocalStorage`
=> Fix result view switching

src/shared/components/results/ResultsView.tsx, src/shared/components/results/__tests__/__snapshots__/ResultsView.spec.tsx.snap, src/shared/components/results/styles/result-card.scss, src/uniparc/components/results/UniParcCard.tsx, src/uniparc/components/results/__tests__/UniParcCard.spec.tsx, src/uniparc/components/results/__tests__/__snapshots__/UniParcCard.spec.tsx.snap, src/uniprotkb/components/results/UniProtKBCard.tsx, src/uniprotkb/components/results/__tests__/UniProtKBCard.spec.tsx, src/uniprotkb/components/results/__tests__/__snapshots__/UniProtKBCard.spec.tsx.snap, src/uniref/components/results/UniRefCard.tsx, src/uniref/components/results/__tests__/UniRefCard.spec.tsx
Create a UniParc card renderer for the result page
New renderer code, and generalise code for other namespace card renderers
Updated tests for generalised code, and added specific snapshot testing for UniParc card renderer
=> add card renderer for UniParc and generalise card code

src/shared/config/apiUrls.ts, src/uniprotkb/adapters/__tests__/extractIsoformsConverter.spec.ts, src/uniprotkb/adapters/allAccessionsConverter.ts, src/uniprotkb/adapters/extractIsoformsConverter.ts, src/uniprotkb/adapters/uniProtkbConverter.ts, src/uniprotkb/components/entry/Entry.tsx, src/uniprotkb/components/entry/SimilarProteins.tsx, src/uniprotkb/components/entry/__tests__/SimilarProteins.spec.tsx, src/uniprotkb/components/entry/__tests__/__mocks__/similarProteinsData.json, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/XrefView.spec.tsx.snap, src/uniprotkb/config/UniProtEntryConfig.tsx, src/uniprotkb/types/entrySection.ts, src/uniref/adapters/uniRefConverter.ts
Adding the "Similar Proteins" section to the UniProtKB entry.
This is the first part of the work required, retrieving the UniRef data, organising it in tabs and displaying the basics. Next step will be to retrieve additional data about the "members" and deciding on the best way to display it based on input from UX.
- Add a data "converter" to extract the list of isoforms and add it to the UI model object
- Create a new component which uses the list of isoforms and canonical accessions to query the UniRef endpoint
- Filter out unwanted data (canonical and isoform accessions from results) and group both by Identity level and by UniProtKB accession
- Display the results in tabs based on groups defined above.
Add a test for the data converter as well as the new `SimilarProteins` component, …
=> 2021 01 similar proteins

src/shared/components/results/ResultsView.tsx
Force unmount/remount of results view when changing the selected columns.
Same hacky approach that we currently do when switching view mode (card/table) or namespace.
Manual testing and switching views, columns, and namespaces
Tackle issue raised to @dlrice that I saw when the Proteomes lineage renderer would be be asked to render data without the lineage data when switching the columns to display
=> hacky fix to force rerendering of results view with new data when changing columns

src/shared/components/results/ResultsView.tsx
Some columns weren't sortable
Get sortable column name before passing to getLocationObjForParams
no change
=> Get sortable column name.

src/shared/components/entry/SequenceView.tsx, src/shared/components/entry/TaxonomyView.tsx, src/shared/components/entry/__tests__/__snapshots__/TaxonomyView.spec.tsx.snap, src/shared/components/error-pages/ObsoleteEntryPage.tsx, src/tools/align/components/results/AlignLabel.tsx, src/tools/blast/components/results/BlastResultTable.tsx, src/uniparc/components/results/UniParcCard.tsx, src/uniprotkb/components/entry/ComputationallyMappedSequences.tsx, src/uniprotkb/components/entry/similar-proteins/SimilarProteins.tsx, src/uniprotkb/components/entry/similar-proteins/SimilarProteinsTable.tsx, src/uniprotkb/components/protein-data-views/KeywordView.tsx, src/uniprotkb/components/protein-data-views/ProteinOverviewView.tsx, src/uniprotkb/components/protein-data-views/ProteomesView.tsx, src/uniprotkb/components/results/UniProtKBCard.tsx, src/uniref/components/data-views/Overview.tsx, src/uniref/components/entry/MembersSection.tsx, src/uniref/components/results/UniRefCard.tsx
Use helper function to create paths to entry pages
Replace everywhere we were using the generatePath function with the different location objects with this helper function
All the tests still pass (generated URLs should stay the same)
=> use getEntryPath() everywhere possible

src/query-builder/utils/parseAndMatchQuery.ts, src/query-builder/utils/queryStringProcessor.ts
Fix issue when injecting a new clause in the query builder via the fake taxonomy facet
=> hotfix for query builder when opened through the taxonomy fake facet

src/shared/config/apiUrls.ts, src/shared/hooks/useDragNDropFile.ts, src/tools/__mocks__/internal-jobs/created.ts, src/tools/__mocks__/internal-jobs/failed-after-submission.ts, src/tools/__mocks__/internal-jobs/failed-before-submission.ts, src/tools/__mocks__/internal-jobs/finished.ts, src/tools/__mocks__/internal-jobs/running.ts, src/tools/adapters/__tests__/parameters.spec.ts, src/tools/adapters/parameters.ts, src/tools/align/config/AlignFormData.ts, src/tools/blast/components/BlastForm.tsx, src/tools/blast/components/__tests__/BlastForm.spec.tsx, src/tools/blast/components/__tests__/__snapshots__/BlastForm.spec.tsx.snap, src/tools/blast/config/BlastFormData.ts, src/tools/blast/types/blastFormParameters.ts, src/tools/blast/types/blastServerParameters.ts, src/tools/components/InputParameters.tsx, src/tools/components/ResultButtons.tsx, src/uniprotkb/components/entry/__tests__/Entry.spec.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap
Have taxonomy filtering working in BLAST search
Now that the backend has been optimised, make available to the user filtering by any level of taxonomy (not just the subset of "organism" as until now).
Also, changed model and code to be able to tackle the newly available excluding taxonomy feature available in the backend (not visible in the frontend yet)
Updated tests and snapshots.
Changed wording to reflect the complete availability of the whole taxonomy tree.
Try running BLAST searches with some higher level taxonomy nodes
Also, reactivated some tests in UniProtKB entry in order to improve test coverage.
=> 2021 02 BLAST form taxonomy filtering

src/tools/blast/components/results/BlastResultSidebar.tsx, src/tools/blast/components/results/BlastResultTable.tsx, src/tools/blast/components/results/__tests__/__snapshots__/BlastResultTable.spec.tsx.snap, src/tools/blast/components/results/styles/BlastResultTable.scss
Prevent crashing the browser when calculating and displaying too many HSPs.
- Display them 10 by 10 instead of just all or nothing as before
- Optimise calculating max scores by simplifying code to use for loops (would cause stack overflow issues otherwise in cases with too manys HSPs)
Run BLAST on a Titin sequence (e.g Q9I7U4), max sure to ask for only 50 hits, but it will still take a while to run
Play with the "+n more" button on a BLAST result
=> 2021 02 optimise BLAST HSPs

src/app/components/HomePage.tsx, src/app/components/__tests__/__snapshots__/HomePage.spec.tsx.snap, src/shared/components/layouts/UniProtHeader.tsx, src/uniprotkb/components/search/SearchContainer.tsx, src/uniprotkb/components/search/__tests__/SearchContainer.spec.tsx, src/uniprotkb/components/search/__tests__/__snapshots__/SearchContainer.spec.tsx.snap
Fix issue where the namespace wouldn't be initialised correctly on the search box in the header after submitting a search from the home page on another namespace than UniProtKB.
Move state around in order to initialise it correctly when the search box is actually rendered in the header and not before
Updated tests and snapshots
=> fix default namespace after searching from home page

src/uniparc/config/UniParcColumnConfiguration.tsx, src/uniparc/config/__tests__/__snapshots__/UniParcColumnConfiguration.spec.tsx.snap
Add missing component in the proteomes renderer of the UniParc results page (table view). Matches behaviour of the current website.
Updated snapshot
=> update the proteomes column renderer for UniParc

src/uniprotkb/config/UniProtKBColumnConfiguration.tsx, src/uniprotkb/config/__tests__/UniProtKBColumnConfiguration.spec.tsx
Saw that some GO columns weren't rendering.
Converted Map to an Array
Add TODOs
**To view search in uniprotkb for (go:0002381)**
=> Hot fix for rendering GO ids and terms.

src/shared/components/results/ResultsContainer.tsx, src/shared/hooks/__tests__/useItemSelect.spec.ts, src/shared/hooks/useItemSelect.ts, src/tools/align/components/results/AlignResult.tsx, src/tools/align/components/results/AlignResultOverview.tsx, src/tools/align/components/results/AlignResultPIM.tsx, src/tools/align/components/results/AlignResultPhyloTree.tsx, src/tools/align/components/results/PhyloTree.tsx, src/tools/blast/components/results/BlastResult.tsx, src/tools/blast/components/results/BlastResultTable.tsx, src/tools/blast/components/results/__tests__/BlastResultTable.spec.tsx, src/tools/components/AlignmentView.tsx, src/tools/components/Overview.tsx, src/tools/components/Wrapped.tsx, src/tools/components/__tests__/AlignmentView.spec.tsx, src/uniprotkb/components/entry/ComputationallyMappedSequences.tsx, src/uniref/components/entry/MembersSection.tsx
The same item selection logic being used in several places.
* Created a `useItemSelect` hook.
* Replaced `handleSelectedEntries` --> `handleItemSelection` as we are only really handling one item at a time.
Wrote useItemSelect tests.
=> 2021 03 use item select

src/uniprotkb/components/entry/similar-proteins/SimilarProteins.tsx
For some UniProtKB entries (e.g. A0A009EBH2) an error appeared in the Similar Proteins section.
When displaying similar proteins, we query for UniRef members of clusters the protein belongs to. We filter out UniParc entries and isoforms, and this sometimes results in an empty list. Because of the groupBy, this translated into an empty object, so the check for empty data before rendering the component was always failing. I've added an early return to fix this issue.
As we are not able to know whether data will be available for similar proteins until the component is created, this causes an issue with the in-page nav. As a workaround it will always display and I've added a message in the component when no data is available.
N.A
=> 2021_03-similar_proteins_nodata

src/app/components/App.tsx, src/app/config/urls.ts, src/shared/components/layouts/__tests__/__snapshots__/UniProtFooter.spec.tsx.snap, src/shared/hooks/useNS.ts
Refactor the routing on the main entry point in order to simplify logic
Now that we have result page renderer for all namespaces, I've refactored the logic in order to have less routes handlers on the main `App` entry point.
Current tests still works, current pages still render
=> refactor entry point routes

src/shared/components/results/ResultsView.tsx, src/supporting-data/locations/components/results/LocationsCard.tsx, src/supporting-data/locations/components/results/__tests__/LocationsCard.spec.tsx, src/supporting-data/locations/components/results/__tests__/__snapshots__/LocationsCard.spec.tsx.snap, src/uniparc/components/results/UniParcCard.tsx, src/uniparc/components/results/__tests__/UniParcCard.spec.tsx, src/uniparc/components/results/__tests__/__snapshots__/UniParcCard.spec.tsx.snap
Create a card renderer for the results of the locations search. Matching figma mockup. [TRM-25595](https://www.ebi.ac.uk/panda/jira/browse/TRM-25595)
Create a card renderer, connect it to the results mega-component.
Snapshot testing + interaction testing (checkbox selection and card click).
Also added tests on interaction testing on UniParc card renderer in order to improve the coverage
=> create and connect locations card in search results

src/shared/components/download/Download.tsx, src/shared/components/download/__tests__/Download.spec.tsx
Column selection in download was not applied.
The list of columns in the state was not the list passed to the url generator.
Added a test to check the url is updated correctly when removing a column.
=> 2021 04 fix download columns

jest.global.setup.ts, package.json, src/shared/components/layouts/ReleaseInfo.tsx, src/shared/utils/__tests__/parseDate.spec.ts, src/shared/utils/parseDate.ts, src/supporting-data/citations/components/LiteratureCitation.tsx, src/supporting-data/citations/config/CitationsColumnConfiguration.tsx, src/tools/dashboard/components/Row.tsx, src/uniparc/components/entry/XRefsSection.tsx, src/uniparc/config/UniParcColumnConfiguration.tsx, src/uniref/components/data-views/Overview.tsx, src/uniref/config/UniRefColumnConfiguration.tsx
Fix issue with some date not being parsed correctly and throwing error on some pages (/proteomes/UP000149066) in some browsers (Firefox and Safari)
Create a wrapper `parseDate` around date parsing and handles some edge cases that we know of.
Makes sure that even if it cannot parse the date, it doesn't return an invalid date that would cause an issue further down the line.
Replace all bare uses of `new Date()` with the new wrapper.
Added tests for wrapper (note that it's running on V8, so would have the same behaviour as Firefox or Safari).
Made sure the rest of tests were running, and that the problematic page was not crashing in Firefox
=> create dateParse helper function in order to avoid invalid dates

src/proteomes/config/ProteomesColumnConfiguration.tsx, src/proteomes/config/__tests__/__snapshots__/ProteomesColumnConfiguration.spec.tsx.snap
Show list of component names as in current website (this wasn't visible before)
Use franklin's ExpandableList
Snapshot update
=> Results proteomes components

src/app/components/App.tsx, src/supporting-data/citations/components/entry/Entry.tsx, src/supporting-data/citations/components/results/CitationsCard.tsx, src/supporting-data/database/components/entry/Entry.tsx, src/supporting-data/diseases/components/entry/Entry.tsx, src/supporting-data/keywords/components/entry/Entry.tsx, src/supporting-data/locations/components/entry/Entry.tsx, src/supporting-data/taxonomy/components/entry/Entry.tsx
Starting point for supporting data entry pages. Doesn't aim to close any specific jira as none of them fit exactly with the mockups.
This is to build upon!
Connect routes for supporting data URLs to components, load data, copy approach for supporting data result page cards, but with more columns rendered.
A lot of copy pasted code, but didn't want to generalise something now when specs are still moving but we need this to be ready yesterday!
No specific unit-test for now.
Checked that the pages where rendering
=> supporting data starting point

src/app/components/App.tsx, src/shared/hooks/useScrollToTop.ts
Scroll to top of the page when changing pathname. [TRM-25715](https://www.ebi.ac.uk/panda/jira/browse/TRM-25715)
Add hook to listen to history changes, when the pathname changes, scroll to the top of the page
No unit test possible (as far as I could think of)
To try, for example, scroll down on the home page, then click on the tile to go to the BLAST form, the top of the form should be visible.
Also, doesn't break the default scroll restauration when clicking the back button (you should go back at the same level on the home page)
=> add hook to scroll to top on pathname change

package.json, src/query-builder/components/QueryBuilder.tsx, src/query-builder/components/TextField.tsx, src/query-builder/components/__tests__/TextField.spec.tsx, src/query-builder/components/__tests__/__snapshots__/QueryBuilder.spec.tsx.snap, src/query-builder/utils/parseAndMatchQuery.ts
Optimised xref query wasn't doing anything
change the logic to handle this special case - replacing "xref" by "database" and the prefix value as value. Also added the parsing counterpart, which is only temporary until backend add the "database" field.
Updated test case for xref and '*' search
=> Fix xref search "hack"

src/shared/components/layouts/ReleaseInfo.tsx
Use a less expensive endpoint to get that information from.  Also allows us to pre-cache the search fields. This is still temporary until a dedicated endpoint exists.
Updated url
N/A
=> Change endpoint to get release info

package.json, src/query-builder/components/QueryBuilder.tsx, src/query-builder/components/__tests__/QueryBuilder.spec.tsx, src/shared/components/results/ResultsFacets.tsx, src/shared/components/results/TaxonomyFacet.tsx, src/shared/components/search/SearchContainer.tsx
When selecting a namespace in the main search and opening advanced search, it should be the same namespace selected
Pass down the namespace as a prop instead of relying on url
Update existing tests
=> 2021 06 fix ns selector

package.json, src/shared/components/results/ResultsFacets.tsx, src/shared/components/results/__tests__/ResultsFacets.spec.tsx, src/shared/components/results/__tests__/__snapshots__/ResultsFacets.spec.tsx.snap
Add icons for reviewed / unreviewed (UniProkb) and reference proteome.
Check facet name and values to add the icon to the ReactNode. Currently not very restrictive in checking and assignment, ok for now but might cause issues in the future if values change.
Added a render which takes into account the new code
=> 2021 06 facet icons

src/shared/components/layouts/styles/side-bar-layout.scss
When clicking on a protvista tooltip, it would be displayed offset on the x and y axis.
Following a suggestion from @aurel-l , remove the `position: sticky` on the content.
- long facet
- infinite scroll still works
- sticky action buttons
- wide tables (already an issue about this)
=> Remove sticky

src/tools/blast/components/results/BlastResultSidebar.tsx
@aurel-l noticed that BLAST facets were missing icons
Reuse the same component to display facets
N/A
=> Use ResultsFacets in BLAST results

package.json, src/proteomes/config/ProteomesColumnConfiguration.tsx, src/supporting-data/citations/config/CitationsColumnConfiguration.tsx, src/supporting-data/diseases/config/DiseasesColumnConfiguration.tsx, src/supporting-data/keywords/config/KeywordsColumnConfiguration.tsx, src/supporting-data/locations/config/LocationsColumnConfiguration.tsx, src/supporting-data/taxonomy/config/TaxonomyColumnConfiguration.tsx, src/uniparc/config/__tests__/__snapshots__/UniParcColumnConfiguration.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/AccessionsView.tsx, src/uniprotkb/components/protein-data-views/FreeTextView.tsx, src/uniprotkb/components/protein-data-views/KeywordView.tsx, src/uniprotkb/components/protein-data-views/ProteinNamesView.tsx, src/uniprotkb/components/protein-data-views/ProteomesView.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/KeywordView.spec.tsx.snap, src/uniprotkb/config/UniProtKBColumnConfiguration.tsx, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap, yarn.lock
Remove the evidence tags on the UniProtKB results columns [TRM-25949](https://www.ebi.ac.uk/panda/jira/browse/TRM-25949)
Remove the evidence tags on *some* of the UniProtKB results columns, use plain text expandable lists instead.
Will need a complete review of all the columns anyway because a lot are using the same components as on the Entry page when it doesn't really make sense within a table cell. And some columns just don't have an implementation yet.
Check the columns that have been modified (see diff view of the column config file)
=> display less evidences in uniprotkb results

src/shared/components/download/Download.tsx, src/shared/components/results/ResultsButtons.tsx, src/shared/components/results/ResultsData.tsx, src/shared/components/results/ResultsDataHeader.tsx, src/shared/config/apiUrls.ts, src/shared/config/namespaceToolTitles.ts, src/tools/config/urls.ts, src/tools/id-mapping/components/results/IDMappingResult.tsx
Add logic to display relevant buttons when looking at ID mapping results.
Pass down props with `namespaceFallback` and a flag to disable the card view switch.
Visual testing only.
=> 2021 06 id mapping buttons

src/uniprotkb/adapters/subcellularLocationConverter.ts, src/uniprotkb/components/entry/GoRibbon.tsx, src/uniprotkb/components/entry/NamesAndTaxonomySection.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
1. Subcell viz section rendering without any subcell data.
2. GO annotations header rendered when GO ribbon has no slim entities
3. Proteomes header rendered without proteomes data
1. Within subcellularLocationConverter.ts check if there is no subcellular data and if not don't add organism data which will cause the section render to falsely believe the section should be rendered.
2. Check if GO data exists. **Note** that the header and loading message appears until data has loaded and if empty these disappear - this is the approach I took but happy if there are nicer suggestions.
3. Check if proteomes data exists
All snapshot updated (the sections are removed)
=> A8 bq10 no subcell viz

src/app/components/App.tsx, src/index.tsx, src/service-worker/client.ts, src/service-worker/reload-flag.ts, src/shared/hooks/useReloadApp.ts
Improve UX when getting a new version of the website
Replace the pop up with a forced refresh whenever the user changes path. The reload will happen on changing the page so it should barely be noticeable by the user as they already expect the page to change.
Using a shared module/flag to mark the application as in need of reloading, and did the similar approach as `useScrollToTop` to detect when is a good time to trigger the forced refresh.
Local production deploys and test update flow when forcing a change in the codebase
=> improve UX when a new version of the app is available

src/shared/config/externalUrls.ts, src/uniprotkb/components/entry/CommunityAnnotationLink.tsx, src/uniprotkb/components/entry/Entry.tsx, src/uniprotkb/components/entry/__tests__/CommunitAnnotationLink.spec.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/CommunitAnnotationLink.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap
"Add a publication" and "Community annotation" links ([jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-26094))
* All entries now have an `Add a publication` link
* Only those entries that have community curation submissions show a link. The vast majority of entries don't have community annotations (https://beta.uniprot.org/uniprotkb?query=(community_pubmed_id:*) has 1,425 results) so I opted to not display any sort of loading indication when querying for community submission count
Unit test and snapshot
=> 2021 08 publication and annotation links

src/query-builder/components/Field.tsx, src/query-builder/components/TextField.tsx, src/query-builder/components/__tests__/TextField.spec.tsx, src/query-builder/utils/fieldInitializer.ts, src/query-builder/utils/parseAndMatchQuery.ts, src/query-builder/utils/queryStringProcessor.ts
Jira: [query builder with database term bug](https://www.ebi.ac.uk/panda/jira/browse/TRM-25580)
There are two ways of generating a query to find entries which are associated with a specific cross-reference (call it `DB`):
1. `xref:DB-*`
2. `database:DB`
The latter is preferred as this results in a quicker SOLR query. However, the front end needs to still parse both of these query strings to populate the query builder form which is the purpose of this PR
1. In `fieldInitializer` detect when term is `'xref'` and `database` is a `queryBit` key to return `*` to correctly populate the form.
2. Handle `clause.queryBits.database` special case in `parseAndMatchQuery`,
3. Reset the `queryBit` when a cross-reference text form input is changed to prevent both `database` and `xref` coexisting as …
=> 2021 08 query builder db bug

src/shared/config/externalUrls.ts, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/CatalyticActivityView.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/CatalyticActivityView.spec.tsx.snap, src/uniprotkb/components/protein-data-views/styles/catalytic-activity-view.scss, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Jira: [Catalytic activity - UI updates](https://www.ebi.ac.uk/panda/jira/browse/TRM-26174):
> 1. The Rhea ID should always be visible (not under collapsed)
> 2. The EC number should be after the reaction, not before
> 3. The toggle to show/hide the reaction should be on a new line
This PR also accidentally covers the jira: [create link to search UniProtKB for EC](https://www.ebi.ac.uk/panda/jira/browse/TRM-23597)
1. Override CSS to hide Rhea ID in `rhea-reaction` and always display in its parent
2. Move the EC number
3. Created a chevron toggle
4. Added respective external URLs
=> 2021 9 catalytic activity UI updates

src/shared/components/results/Results.tsx, src/shared/components/results/ResultsData.tsx, src/shared/components/results/__tests__/ResultsData.spec.tsx, src/shared/hooks/useNSQuery.ts, src/tools/peptide-search/components/results/PeptideSearchResult.tsx, src/uniprotkb/utils/resultsUtils.ts
Redirect to entry page https://www.ebi.ac.uk/panda/jira/browse/TRM-26172
Different behaviour to the one in the Jira as difficult to define what is a "subsequent query".
Redirect to the entry page if only one result and if the search matches the accession or the ID of that result.
Also, fixed `?direct` approach that wasn't passed down the components as needed. Done by removing prop drilling and getting the value of that flag only where needed.
Added tests for all 3 cases of redirecting to entry page. Testing redirect (through `history.location.pathname`)
Can check behaviour by searching for an accession ("P05067"), an ID ("KVD30_HUMAN", some ID searches like "A4_HUMAN" return multiple results so won't work for all IDs), or an ID of any namespace ("9606" in taxonomy).
=> 2021 09 direct results

jest.setup.ts
Seeing an issue where our [tests are timing out](https://gitlab.ebi.ac.uk/uniprot/uniprot-website/uniprot-website/-/jobs/495940) on the gitlab CI runners I’m guessing because:
- not all runners have the specs
- the machines are shared and maybe another process is stealing resources
This PR just pushes the timeout to 30s.
=> Increase jest test timeout.

src/proteomes/config/__tests__/ProteomesColumnConfiguration.spec.tsx, src/proteomes/config/__tests__/__snapshots__/ProteomesColumnConfiguration.spec.tsx.snap, src/shared/__test-helpers__/queryMoreButton.ts, src/shared/__test-helpers__/testColumnConfiguration.tsx, src/shared/utils/__tests__/utils.spec.ts, src/shared/utils/utils.ts, src/supporting-data/citations/config/__tests__/CitationsColumnConfiguration.spec.tsx, src/supporting-data/database/config/__tests__/DatabaseColumnConfiguration.spec.tsx, src/supporting-data/diseases/config/__tests__/DiseasesColumnConfiguration.spec.tsx, src/supporting-data/keywords/config/__tests__/KeywordsColumnConfiguration.spec.tsx, src/supporting-data/locations/config/__tests__/LocationsColumnConfiguration.spec.tsx, src/supporting-data/taxonomy/config/__tests__/TaxonomyColumnConfiguration.spec.tsx, src/uniparc/config/__tests__/UniParcColumnConfiguration.spec.tsx, src/uniparc/config/__tests__/UniParcXRefsColumnConfiguration.spec.tsx, src/uniparc/config/__tests__/__snapshots__/UniParcColumnConfiguration.spec.tsx.snap, src/uniprotkb/components/protein-data-views/CSVView.tsx, src/uniprotkb/components/protein-data-views/__tests__/CSVView.spec.tsx, src/uniprotkb/config/UniProtKBColumnConfiguration.tsx, src/uniprotkb/config/__tests__/UniProtKBColumnConfiguration.spec.tsx, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap, src/uniref/config/__tests__/UniRefColumnConfiguration.spec.tsx
Jira: [Protein names missing "subNames"](https://www.ebi.ac.uk/panda/jira/browse/TRM-26211)
Gene Names and Protein Names column renderers doing very similar things so:
1. Created `deepFindAllByKey` function to extract all of the `value` names for both genes and proteins
2. Created `CSVView` component to render this (including the missing submission names)
- Create unit tests for `CSVView` and `deepFindAllByKey`
- Update `UniProtKBColumnConfiguration` snapshot tests to also check to see if there is a "more" button and if so click this and create a new snapshot from this.
As the jira states visit http://localhost:8080/uniprotkb?query=uncharacterized%20protein%20koala and look at the protein names column
=> Submission protein names

src/uniprotkb/components/protein-data-views/ProteinOverviewView.tsx, src/uniprotkb/components/protein-data-views/__tests__/ProteinOverview.spec.tsx
@xwatkins noticed that the submission name is missing from the protein overview.
If recommended name not present, use the first submission name.
Unit test created
- http://localhost:8080/uniprotkb?query=A0A0M9JJ85%2A
- http://localhost:8080/uniprotkb/A0A0M9JJ85/entry
=> More missing protein submission names

src/shared/hooks/__tests__/useDataApi.spec.ts, src/shared/hooks/__tests__/useLocalStorage.spec.ts, src/shared/hooks/useLocalStorage.ts
Fix an issue when using the same useLocalStorage hook but changing its key.
It was still using the value for the previous key, so added a useEffect changing the state of the hook when the key changes.
Use stringified versions of the defaultValue in order to not enter in infinite loops when the useEffects depended on it and using complex values.
Added a specific test for when the key used in the hook changes
=> fix useLocalStorage

src/tools/adapters/parameters.ts, src/uniprotkb/__mocks__/uniProtKBEntryModelData.ts, src/uniprotkb/adapters/__tests__/interactionConverter.spec.ts, src/uniprotkb/config/UniProtKBColumnConfiguration.tsx, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap, src/uniprotkb/utils/__tests__/resultsUtils.spec.ts, src/uniprotkb/utils/resultsUtils.ts
https://www.ebi.ac.uk/panda/jira/browse/TRM-24893
In the UniProtkb results table, the "interacts with" columns always displayed the "current" accession instead of the interactor.
Add logic to pick either interactantOne or interactantTwo as the interactant to display.
Updated the example data to reflect reality, as well as corresponding snapshots.
=> Fix interaction column renderer

src/app/components/styles/app.scss, src/shared/styles/helper.module.scss, src/uniprotkb/components/entry/FunctionSection.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/CatalyticActivityView.tsx, src/uniprotkb/components/protein-data-views/FreeTextView.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/CatalyticActivityView.spec.tsx.snap
1. Duplicate pathway notes in function section
2. Inconsistent title casing
1. Removed one
2. Created an app level `capitalize` class and used this instead of inline styles
Snapshot updates
=> Function section tidy up

src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/AccessionsView.tsx
Looking at https://beta.uniprot.org/uniprotkb/A8BQ10/entry I noticed the `Secondary accessions` info list titled rendered without any children
Check if there are secondary accessions first. This needs to be handled here as I can't see a reliable way to check for null-like react elements in the `InfoList`.
=> Empty secondary accessions

src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/DiseaseInvolvementView.tsx, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Show disease comments which consist of only a note ([Jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-26305))
- Also show comments which contain only a note.
- Followed the structure of the data (and the current site) and listed associated publications next to the notes.
As the jira states P02511 has a disease comment consisting of only a note
=> 2021 10 missing disease comment

src/query-builder/utils/__tests__/__mocks__/clauseQueryTestData.ts, src/query-builder/utils/queryStringProcessor.ts
- When parsing queries with double quotation marks and spaces additional, unneeded, double quotation marks were being added
- [Jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-26348)
- Detect if the query starts and ends with `"` and if so, don't add more
- Unit test written
=> Parse query with space and quoations

src/tools/align/components/AlignForm.tsx, src/tools/blast/components/BlastForm.tsx, src/tools/blast/components/__tests__/__snapshots__/BlastForm.spec.tsx.snap, src/tools/id-mapping/components/IDMappingForm.tsx, src/tools/id-mapping/components/__tests__/__snapshots__/IDMappingForm.spec.tsx.snap, src/tools/peptide-search/components/PeptideSearchForm.tsx
Disable forms when the text input is empty. https://www.ebi.ac.uk/panda/jira/browse/TRM-26157
Disable by default, adjust conditions to disable in the useEffect of each form.
- Updated snapshots
- Manually made sure the forms were disabled by default, enabled when in the right conditions, re-disabled when returning to empty text content. And also, checked that they weren't disabled by default when resubmitting an existing job.
=> disable forms when empty

src/shared/hooks/useTextFileInput.ts
Bug fix: useTextFileInput unresponsive to loading same file twice [[jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-26469)]
`inputRef.current.value = ''` inside the hook
none
=> useTextFileInput: reset input ref to handle the case that a user loads the same file twice

package.json, src/shared/styles/_settings.scss, src/types/protvista-structure.d.ts, src/types/protvista-uniprot.d.ts, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/PDBView.tsx
[PDB structure viewer not loading structures on row click](https://www.ebi.ac.uk/panda/jira/browse/TRM-26476)
- Replicate Covid portal changes where `protvista-uniprot-structure` is used
- Had to bump `$z-index-high` to `40000`
- Removed `protvista-structure`
None
=> 2021 11 structure table bug

package.json, src/shared/components/action-buttons/CustomiseButton.tsx, src/shared/components/action-buttons/styles/customise-button.module.scss, src/shared/components/column-select/ColumnSelect.tsx, src/shared/components/column-select/__tests__/ColumnSelect.spec.tsx, src/shared/components/column-select/__tests__/__snapshots__/ColumnSelect.spec.tsx.snap, src/shared/components/column-select/styles/column-select-drag-drop.scss, src/shared/components/column-select/styles/column-select.scss, src/shared/components/column-select/utils/__tests__/index.spec.tsx, src/shared/components/customise-table/CustomiseTable.tsx, src/shared/components/customise-table/__tests__/CustomiseTable.spec.tsx, src/shared/components/customise-table/__tests__/__snapshots__/CustomiseTable.spec.tsx.snap, src/shared/components/customise-table/styles/customise-table.scss, src/shared/components/download/Download.tsx, src/shared/components/entry/styles/entry-page.scss, src/shared/styles/sticky.module.scss, src/tools/align/components/AlignForm.tsx, src/tools/align/components/results/AlignResult.tsx, src/tools/blast/components/BlastForm.tsx, src/tools/blast/components/results/BlastResult.tsx, src/tools/id-mapping/components/IDMappingForm.tsx, src/tools/peptide-search/components/PeptideSearchForm.tsx, src/uniprotkb/components/entry/Entry.tsx, src/uniprotkb/types/resultsTypes.ts
Modifications needed to the customise column component https://www.ebi.ac.uk/panda/jira/browse/TRM-26084
From the jira (some points were out of date):
1. ~Customise columns" in H2 text style~ title was already in the sliding panel title area
2. Change tab name "Links" to "External links" -> in this PR
3. Make the tabs sticky -> in this PR (there were already rules in CSS, but was missing a class to apply it)
4. ~Add placeholder to search bar "Search for columns"~ had already been set recently
5. Move the "Reset to default" button next to the "Close" button, see mockup -> in this PR
Move tests around, specifically the on regarding resetting as it changed component
=> changes to customise columns sliding panel

src/tools/dashboard/components/Row.tsx, src/tools/state/getCheckJobStatus.ts, src/tools/utils/index.tsx
Don't let the user go to a results page if there are no results https://www.ebi.ac.uk/panda/jira/browse/TRM-26302 & https://www.ebi.ac.uk/panda/jira/browse/TRM-26345
Remove links in the status text, the result card, and the popup
Manual testing with P05635 to Allergome (ID Mapping), and P80488 (BLAST)
=> no link to results page when no results

src/uniprotkb/components/protein-data-views/SubCellViz.tsx
Handle locations which are membranes or "part". [[Jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-25569)]
- From seen locations extract classnames that start with `mp_` or `part_` and convert these into IDs.
- Apply styles with selector `[class*="mp_"] .coloured, svg [class*="part_"] .coloured`
None
Accession A1L3X0 is a good example.
=> Subcell viz membranes

src/proteomes/__mocks__/proteomesEntryModelData.ts, src/proteomes/adapters/proteomesConverter.ts, src/proteomes/components/__tests__/__snapshots__/BuscoView.spec.tsx.snap, src/proteomes/components/entry/ComponentsButtons.tsx, src/proteomes/components/entry/__tests__/__snapshots__/Components.spec.tsx.snap, src/proteomes/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/proteomes/components/results/__tests__/__snapshots__/ProteomesCard.spec.tsx.snap, src/proteomes/config/__tests__/__snapshots__/ProteomesColumnConfiguration.spec.tsx.snap, src/shared/components/download/Download.tsx, src/shared/config/testingApiUrls.ts
Update proteomes model for backend changes [[jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-26657)]
- Model mostly unchanged except for `proteinCount` is now being provided. Note that there is an open jira regarding the slight inaccuracies of `proteinCount`.
- Download component: format selected as long number as proteomes count often exceeds 999.
=> 2021 13 schema updates proteomes

package.json, src/app/config/urls.ts, src/service-worker/__tests__/url-patterns.spec.ts, src/shared/components/entry/__tests__/__snapshots__/SequenceView.spec.tsx.snap, src/shared/config/apiUrls.ts, src/shared/config/testingApiUrls.ts, src/shared/utils/__tests__/getFASTAFromAccession.spec.ts, src/supporting-data/citations/adapters/citationsConverter.ts, src/supporting-data/citations/components/LiteratureCitation.tsx, src/supporting-data/citations/components/__tests__/LiteratureCitation.spec.tsx, src/uniprotkb/components/entry/__tests__/__mocks__/entryPublicationsData.ts, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
- Check model changes for UniProtKB
- Update new url path without `/accession`
- Handle `locator` field in Citations
- There were no changes to the model
- All paths were updated and test cases updated. Checked in browser.
- Managed to dig up the old code from uuw to see how the urls corresponding to `locator` were handled and translated the logic. In the process, realised that ARVO was missing, Leo is looking into that and will create a subsequent Jira.
Added a test to check the generation of the url was correct.
Examples to try: O64948, P98060
=> 2021 13 schema updates uniprotkb

src/shared/components/entry/TaxonomyView.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/config/UniProtKBColumnConfiguration.tsx, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Column renderer for Features [[jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-26690)]
1. Search in UniProtKB
2. Customise columns
3. Add the feature column. Notice that there are two feature columns. Back-end have already removed the duplicate and will deploy the change soon.
* Add column renderer
* Noticed that Virus Host uses <p> which creates extra space around each element
=> 2021 13 features column

src/app/components/App.tsx
Redirect what will be landing pages to the corresponding star search for now https://www.ebi.ac.uk/panda/jira/browse/TRM-26846
This is after realising that some users ended up there sometimes (URL editing?) and would see a no results page
Reuse the ResultsOrLanding helper component and point to a Redirect component reusing the current location and replacing the search part of the location
Manual testing
=> redirect all search pages without a search query to the star search

src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/UniProtKBEvidenceTag.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/UniProtEvidenceTag.spec.tsx.snap, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap, src/uniprotkb/config/evidenceCodes.ts
Some automatic annotation evidence tags were showing a gold ribbon.
Update the definition for the corresponding ECO code. Also added the content of the `description` field to the body, as it helps disambiguate some of the tags.
=> 2021 15 slim sets  correct evidence

src/uniprotkb/adapters/slimming/GORibbonHandler.ts, src/uniprotkb/adapters/slimming/__tests__/__mocks__/go-ribbon-subjects.ts, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/UniProtKBEvidenceTag.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/UniProtEvidenceTag.spec.tsx.snap, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap, src/uniprotkb/config/evidenceCodes.ts
Update the count of evidences to include the ones defined in properties
Add 1 if there is a property defined for evidence
Update mocks
=> 2021_15-slim_sets--evidence-count

package.json, src/uniprotkb/components/entry/StructureSection.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/PDBView.tsx, src/uniprotkb/components/protein-data-views/StructureView.tsx, src/uniprotkb/components/protein-data-views/XRefView.tsx
With AF, every single entry will eventually have structures to display. Currently we are only displaying the structure if PDB information is available.
Always display the structure, and use the protvista-uniprot-structure component. Kept the PDBView component datatable only as it's still used for xrefs, and added a comment .
Update snapshots.
Had to bump down the coverage as some of the component display is now handled in the web components.
=> Always display structure viewer

src/uniprotkb/adapters/slimming/GORibbonHandler.ts, src/uniprotkb/components/protein-data-views/ProteinOverviewView.tsx
Mainly get gene names from more places in the data
Discovered through https://sentry.io/organizations/uniprot/issues/2817748403/
Get gene names from orderedLocusNames or orfNames, to match the current website behaviour
Remove the warning when no gene name, this might happen and is correct
Currents tests still running
Check the title of the go ribbon cells (mouse over)
Check the protein overview at the top of a entry page
Exampe test with:
P05067: no change
Q90023: fix the empty "Gene: " displayed on current beta by using the orderedLocusNames
A0A5K4F3G5: no gene name, correctly not displaying it, no warning raised
You could check with more examples from https://sentry.io/organizations/uniprot/issues/2817748403/tags/transaction/
=> 2021 16 gene names

package.json, src/shared/components/entry/SequenceView.tsx, src/shared/components/entry/__tests__/__snapshots__/SequenceView.spec.tsx.snap, src/shared/components/entry/styles/sequence-view.module.css, src/types/custom.d.ts, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/config/UniProtKBColumnConfiguration.tsx, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Modifications to the Isoforms sections https://www.ebi.ac.uk/panda/jira/browse/TRM-26879 & https://www.ebi.ac.uk/panda/jira/browse/TRM-26631
- When on isoform page, display only the isoform sequence, opened
- Added a quick link back to the canonical
- Added link to UniParc and UniRef for each isoform
Updated snapshots & checked on canonical page and corresponding isoform pages
=> Isoform section

src/app/config/urls.ts, src/shared/utils/__tests__/__snapshots__/utils.spec.ts.snap, src/shared/utils/__tests__/utils.spec.ts, src/shared/utils/utils.tsx, src/uniprotkb/components/entry/EntryPublications.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/UniProtKBFeaturesView.tsx
Add link to BLAST with subsequence in Publication cited for text. See http://localhost:8080/uniprotkb/P25719/publications
Check for matching regex and replace text
Adding checks for Regex function
=> Parse publication cited for to include BLAST links

src/shared/components/results/__tests__/__snapshots__/ResultsData.spec.tsx.snap, src/tools/peptide-search/components/results/__tests__/__snapshots__/PeptideSearchResult.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/CatalyticActivityView.tsx, src/uniprotkb/components/protein-data-views/ProteinNamesView.tsx, src/uniprotkb/components/protein-data-views/ProteinOverviewView.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/CatalyticActivityView.spec.tsx.snap, src/uniprotkb/components/results/__tests__/__snapshots__/UniProtKBCard.spec.tsx.snap, src/uniprotkb/config/UniProtKBColumnConfiguration.tsx, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Address issues with EC numbers:
- in the results table, they were displayed as a list of ids with no separation
- links to UniProt/Enzyme search and Rhea were missing
- inconsistent use of the EC view component
https://www.ebi.ac.uk/panda/jira/browse/TRM-26641
Re-factor EC view component to add optional links, and horizontal/vertical view, re-use the component throughout.
Checked with Marija that it was what was expected.
=> EC numbers

src/supporting-data/keywords/components/entry/Entry.tsx
Other resources link to UniProt keywords by using an old format, without the `KW-` prefix.
If the submitted accession is ony made of numbers, update the location by adding `KW-` to the number.
N/A
=> Add redirect if missing 'KW-'

src/tools/components/SequenceSearchLoader.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/FreeTextView.tsx, src/uniprotkb/components/protein-data-views/__tests__/FreeTextView.spec.tsx, src/uniprotkb/components/protein-data-views/__tests__/__mocks__/freeTextUIData.ts, src/uniprotkb/utils/index.ts
[Sequence caution - parse "AC " to create hyperlink](https://www.ebi.ac.uk/panda/jira/browse/TRM-26896)
Split caution text by whitespace and iterate to find any instances of an AC preceding an accession and update with link if found.
* Snapshots updated
* New unit tests
=> Kanban ac accession

src/proteomes/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/supporting-data/citations/adapters/citationsConverter.ts, src/supporting-data/citations/components/LiteratureCitation.tsx, src/uniprotkb/components/entry/EntryPublications.tsx
Address multiple issues:
1. https://www.ebi.ac.uk/panda/jira/browse/TRM-27060
2. https://www.ebi.ac.uk/panda/jira/browse/TRM-27046
3. https://www.ebi.ac.uk/panda/jira/browse/TRM-27045
4. https://www.ebi.ac.uk/panda/jira/browse/TRM-27055
- When the citation type is not one of the main types, display it on the right above the date information.
- Group comment types and display them all. Add search link for "Strain".
- Display `authorGroup` in Authors component if it's there
=> Kanban missing publication info

src/shared/components/entry/SequenceView.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
[Sequence section should include the sequence status (fragment or not)](https://www.ebi.ac.uk/panda/jira/browse/TRM-27039)
* Return `null` if no sequence
* Return `infoListComponent` and `canonicalComponent` if no `alternativeProducts`
* Return everything otherwise
http://localhost:8080/uniprotkb/C0HJU3/entry#sequence
Updated
=> Missing sequence info

package.json, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/DiseaseInvolvementView.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/DiseaseInvolvementView.spec.tsx.snap, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap, yarn.lock
[Display OMIM and UniProt's Disease page link in UniProtKB disease section](https://www.ebi.ac.uk/panda/jira/browse/TRM-26261)
- Create link
- Add xref name before xref link
- Upgrade franklin
- Updated snapshots
=> Disease link and xref name

src/uniprotkb/components/entry/Entry.tsx, src/uniprotkb/components/entry/SubcellularLocationSection.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/SubCellViz.tsx, src/uniprotkb/components/protein-data-views/SubcellularLocationWithVizView.tsx, src/uniprotkb/components/protein-data-views/styles/subcellular-location-go-view.module.scss
- [Subcellular location card present in entry without subcell info](https://www.ebi.ac.uk/panda/jira/browse/TRM-26645)
- [Display subcellular annotation info even if there is no subcellular location visualisation](https://www.ebi.ac.uk/panda/jira/browse/TRM-26974)
- [Subcellviz: Handle case where there is no data to display](https://www.ebi.ac.uk/panda/jira/browse/TRM-26822)
- Create `subcellularLocationSectionHasContent` to determine if there is any content to render
- If no locations or it's a virus-related entry but does have notes, return these
- If no locations or notes, return message indicating this (this used to be done by within CSS)
- If nothing for the UniProt tab but there is something for the GO tab, make GO tab the initial default selected
**Note**: Marija has viewed the …
=> Subcell section handle lack of data

src/app/components/home-page/UniProtData.tsx, src/proteomes/adapters/proteomesConverter.ts, src/proteomes/components/entry/Entry.tsx, src/proteomes/components/entry/Overview.tsx, src/proteomes/components/entry/PanProteome.tsx, src/proteomes/components/entry/__tests__/PanProteome.spec.tsx, src/proteomes/components/entry/__tests__/__snapshots__/PanProteome.spec.tsx.snap, src/proteomes/config/ProteomesColumnConfiguration.tsx, src/proteomes/config/__tests__/ProteomesColumnConfiguration.spec.tsx, src/shared/components/layouts/ReleaseInfo.tsx, src/shared/components/layouts/__tests__/__snapshots__/UniProtFooter.spec.tsx.snap, src/shared/components/layouts/styles/release-info.scss, src/shared/config/ftpUrls.ts, src/shared/styles/blur-loading.module.scss
[Missing link to pan proteome in Proteome entry Overview](https://www.ebi.ac.uk/panda/jira/browse/TRM-27062)
- If `panproteome` is provided, check to see if it matches the current entry. If so, use that. If not, load the corresponding `panproteome` entry.
- Handle loading state at the same place as the rest of the entry (Loader on the main area of the page)
- Added more ftp config
I have made a few assumptions as there wasn't enough people to discuss the following questions:
- ~If a `panproteome` ID is present is it ever different to the the current entry ID? If so, what is an example?~
- UP000000211 & UP000000532
- ~Should we create a link to the pan proteome entry page (if different) as well as just the FASTA FTP download link?~
- Yes, like in the current website
- …
=> Panproteome

src/shared/contexts/DatabaseInfoMaps.tsx
Tries to handle the possible reasons behind the complete white page reports in hotjar.
Since loading the db info maps data is blocking to render the whole site, give a UI feedback to the user if anything goes wrong.
(Note that the white page issues might still be caused by other reasons, I'm thinking mainly with network issues when loading the main JS chunks)
Most of the time, the user won't have time to notice anything, but:
- If the network is really slow, displays a Loader component
- If there's been an issue loading the data, displays an error component
=> At least there's a cue to understand what's going on from the user's point of view => might retry to load, or wait to have a better network
Manual testing: devtools network request blocking for …
=> DB Info Map loading issues

src/app/components/App.tsx, src/help/components/contextual/ContextualHelp.tsx, src/help/components/contextual/ContextualHelpContainer.tsx, src/help/components/contextual/SideButtons.tsx, src/help/components/contextual/styles/side-buttons.module.scss, src/help/components/entry/Entry.tsx, src/help/components/entry/__tests__/Entry.spec.tsx, src/help/components/results/Results.tsx
Add contextual help side button and start adding some content in it
- Move all side buttons (help + feedback) in their own component
- Use router for contextual internal routing logic and reuse components
Updated test for existing component
Manual testing for now (behaviour will likely change in the future, so no point at this point)
=> contextual help - side button & content

src/help/components/contextual/Landing.tsx, src/help/components/contextual/NavigationBar.tsx, src/help/components/contextual/styles/landing.module.css, src/help/components/contextual/styles/search-bar.module.scss, src/help/components/contextual/styles/shortcuts.module.scss, src/shared/styles/_settings.scss
Landing page for the contextual help (part of https://www.ebi.ac.uk/panda/jira/browse/TRM-27303)
Add content to the landing page:
- If no help content in the page, default to a list of links (similar to the full page Help Centre)
- If help content in the page, retrieve it and display links
- Retrieve title for each article (limitation of the API, probably need an "accessions" endpoint for the help endpoints too)
- Visual difference for those that are in the user's view (probably need to iterate on that later)
- Scroll in the middle of the panel the help article corresponding to the first one in the user's view
Manual test
=> 2022 02 contextual help panel landing

src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryExternalLinks.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/KeywordView.tsx, src/uniprotkb/components/protein-data-views/SubcellularLocationGOView.tsx, src/uniprotkb/components/protein-data-views/SubcellularLocationView.tsx, src/uniprotkb/components/protein-data-views/SubcellularLocationWithVizView.tsx, src/uniprotkb/components/protein-data-views/XRefView.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/KeywordView.spec.tsx.snap, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/SubcellularLocationGOView.spec.tsx.snap, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/XrefView.spec.tsx.snap, src/uniprotkb/components/protein-data-views/styles/sub-cell-viz.scss, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Add links to supporting data pages (instead of current website's contextual help) -> from sprint board
Also, https://www.ebi.ac.uk/panda/jira/browse/TRM-26988 & https://www.ebi.ac.uk/panda/jira/browse/TRM-26761
On UniProtKB pages, replace where we refer to databases, subcellular locations, and keywords, with links.
Also, tackled the 2 above jiras as part of this because I touched the subcell location part.
For subcell location, link to ID.
For Databases and remaining Keywords (categories), we don't have IDs in the data so link to a search and redirect if we can (if only 1 result). That's the best I could do with the data we had at this moment.
Updated snapshots + manual checks
=> 2022 02 links to supporting data

package.json, src/shared/components/action-buttons/ShareDropdown.tsx, src/shared/components/download/Download.tsx, src/shared/components/results/Results.tsx, src/shared/components/results/ResultsButtons.tsx, src/shared/components/results/ResultsData.tsx, src/shared/components/results/__tests__/Results.spec.tsx, src/shared/components/results/__tests__/ResultsData.spec.tsx, src/shared/hooks/useColumnNames.ts, src/shared/hooks/useColumns.tsx, src/shared/hooks/useNSQuery.ts, src/shared/hooks/useViewMode.ts, src/supporting-data/database/config/DatabaseColumnConfiguration.tsx, src/tools/blast/components/results/BlastResult.tsx, src/tools/blast/components/results/BlastResultLocalFacets.tsx, src/tools/blast/components/results/BlastResultSidebar.tsx, src/tools/id-mapping/components/results/IDMappingResult.tsx, src/tools/id-mapping/components/results/__tests__/IDMappingResult.spec.tsx, src/uniparc/components/entry/Entry.tsx, src/uniprotkb/components/entry/EntryPublications.tsx, src/uniprotkb/components/entry/EntryPublicationsFacets.tsx, src/uniprotkb/utils/__tests__/resultsUtils.spec.ts, src/uniprotkb/utils/resultsUtils.ts, src/uniref/components/entry/MembersFacets.tsx, src/uniref/components/entry/MembersSection.tsx
Consume view and fields parameters from the url.
- Create two new hooks: `useViewMode` and `useColumnNames` which holds most of the logic to determine which of localStorage or the url should be used.
- If invalid param/value send a message to user
- Keep view and fields in URL when switching viewMode and sorting columns
- Updated tests
=> 2022 03 share url consume v2

package.json, src/shared/components/download/Download.tsx, src/shared/components/results/Results.tsx, src/shared/components/results/ResultsButtons.tsx, src/shared/components/results/ResultsData.tsx, src/shared/components/results/__tests__/Results.spec.tsx, src/shared/hooks/useColumns.tsx, src/shared/hooks/useNSQuery.ts, src/supporting-data/database/config/DatabaseColumnConfiguration.tsx, src/tools/blast/components/results/BlastResult.tsx, src/tools/blast/components/results/BlastResultLocalFacets.tsx, src/tools/blast/components/results/BlastResultSidebar.tsx, src/tools/id-mapping/components/results/IDMappingResult.tsx, src/uniparc/components/entry/Entry.tsx, src/uniprotkb/components/entry/EntryPublications.tsx, src/uniprotkb/components/entry/EntryPublicationsFacets.tsx, src/uniprotkb/utils/__tests__/resultsUtils.spec.ts, src/uniprotkb/utils/resultsUtils.ts, src/uniref/components/entry/MembersFacets.tsx, src/uniref/components/entry/MembersSection.tsx
Consume view and fields parameters from the url.
- Update `getParamsFromURL` to
- Extract view and fields
- Accept an optional namespace argument and use this to determine if valid columns names have been passed
- Return any invalid params/values
- Use output of `getParamsFromURL` to determine which view and fields to use through result fetching
- If invalid param/value send a message to user
- Keep view and fields in URL when switching viewMode and sorting columns
- Updated tests
=> 2022 03 share url consume

src/app/config/urls.ts, src/shared/utils/__tests__/url.spec.ts, src/tools/align/components/results/AlignResult.tsx, src/tools/align/types/alignServerParameters.ts, src/tools/blast/components/results/BlastResult.tsx, src/tools/blast/config/BlastFormData.ts, src/tools/blast/config/__tests__/BlastFormData.spec.ts, src/tools/blast/types/blastServerParameters.ts, src/tools/dashboard/components/Row.tsx, src/tools/id-mapping/components/results/IDMappingResult.tsx, src/tools/utils/__tests__/__snapshots__/index.spec.tsx.snap, src/tools/utils/index.tsx
Add namespace to paths for id mapping (optional) and BLAST results.
Unify and simplify path generation.
Tried different job types, from the dashboard and from in-message links. For ID mapping, experimented with different target databases. Also checked that tabs still worked within tools results (this was an issue for BLAST).
Added a simple test for the database to namespace logic.
=> 2022 94 tools adv search  path

src/app/config/urls.ts, src/shared/components/search/SearchContainer.tsx, src/shared/components/search/__tests__/SearchContainer.spec.tsx, src/shared/components/search/__tests__/__snapshots__/SearchContainer.spec.tsx.snap, src/tools/id-mapping/components/results/IDMappingResult.tsx
- Add job ID to search bar on tools results for URL location (namespace + job-id)
- Remove/disable advanced search for Align results page
Determine if the user is on a tool results page and if so extract the job id and place this in the main search input.
Updated unit tests
=> 2022 04 tools adv search search bar2

src/app/config/urls.ts, src/shared/hooks/useNS.ts
- Fix url route to `id-mapping/unref`
- Reflect tool results namespace in toolbar
- Reuse `databaseToNamespace`
- Adapt `useNS`
None
=> 2022 04 tools adv search fixes

src/shared/components/search/SearchContainer.tsx, src/shared/config/apiUrls.ts, src/tools/blast/components/results/BlastResult.tsx, src/tools/config/urls.ts, src/tools/id-mapping/components/results/IDMappingResult.tsx
Add filtering according to the URL for ID Mapping, Peptide Search, and BLAST results.
Make the search bar work when submitting a search from there
ID Mapping => pass query (without the job) to the ID mapping results endpoint
Peptide Search & BLAST => pass query (without the job) to the accessions endpoint (unable to check much because it's not supported yet + endpoint glitching, I'm assuming because of the ongoing update)
Just a bit of manual testing for now
=> 2022 04 tools adv search id mapping search

src/tools/blast/components/results/BlastResult.tsx, src/tools/id-mapping/components/results/IDMappingResult.tsx, src/tools/peptide-search/components/PeptideSearchForm.tsx, src/tools/peptide-search/components/results/PeptideSearchResult.tsx, src/tools/peptide-search/components/results/__tests__/__snapshots__/PeptideSearchResult.spec.tsx.snap
1. Standardise tool results titles
2. Fix peptide search form from growing
1. Update title wording
2. Truncate long peptide sequences with ellipsis (defaults to 30) 
=> 2022 04 tools adv search titles & peptide search form fix

src/app/config/urls.ts, src/tools/align/components/results/AlignResult.tsx, src/tools/blast/components/results/BlastResult.tsx, src/tools/id-mapping/components/results/IDMappingResult.tsx, src/tools/id-mapping/components/results/IDMappingResultTable.tsx, src/tools/id-mapping/components/results/__tests__/IDMappingResult.spec.tsx, src/tools/peptide-search/components/results/PeptideSearchResult.tsx, src/tools/peptide-search/components/results/PeptideSearchResultTable.tsx, src/tools/peptide-search/components/results/__tests__/__snapshots__/PeptideSearchResult.spec.tsx.snap, src/tools/utils/hooks.ts
Add tab logic for all tools results.
Add tab logic for all tools results, including correct routing, and a bit of refactor in order to have as much as possible parallel logic in all files (to help future refactors) + isolate custom hook to redirect to "overview" when no subpage is specified.
Doesn't include the actual content of the added tabs.
Manual test + update snapshots
=> add tabs logic to all tools results

package.json, src/app/components/home-page/HomePage.tsx, src/query-builder/components/QueryBuilder.tsx, src/query-builder/components/__tests__/QueryBuilder.spec.tsx, src/shared/components/layouts/UniProtHeader.tsx, src/shared/components/results/TaxonomyFacet.tsx, src/shared/components/search/SearchContainer.tsx, src/shared/components/search/__tests__/SearchContainer.spec.tsx, src/shared/types/namespaces.ts, yarn.lock
Use a tool results search space for all jobs and use franklin's corresponding color.
- Create `searchspace` which is all searchable namespaces and tool results. This is only visible when there is a job in the url.
- Remove `job:<jobId>` from search input when viewing tool results
None
=> 2022 04 tools adv search tool results searchspace

src/tools/components/APIRequest.tsx, src/tools/components/InputParameters.tsx, src/tools/components/styles/extra-tabs.module.css, src/tools/components/styles/input-parameters.module.css, src/tools/id-mapping/components/results/IDMappingResult.tsx, src/tools/peptide-search/components/results/PeptideSearchResult.tsx
Add content to the API Request tab
Similar approach as the one taken for the Input Parameters tabs changes (pass local job parameters, if any).
Display a fallback snippet if no local job information
Also, fixed issue with long content in CodeBlock component
Manual checks
=> handle ID Mapping and Peptide Search in API Request tab

src/shared/components/download/Download.tsx, src/shared/components/download/__tests__/Download.spec.tsx, src/shared/config/apiUrls.ts, src/tools/id-mapping/components/results/IDMappingResultTable.tsx
Use ID mapping results endpoint for downloads
- In `getDownloadUrl` if `base` is present use this for the endpoint
- Don't pass accessions to `ResultsButtons` in `IDMappingResultTable`
Add unit tests
=> 2022 04 download id mapping

src/shared/components/results/__tests__/Results.spec.tsx, src/shared/config/apiUrls.ts, src/shared/hooks/useColumns.tsx, src/tools/config/urls.ts, src/tools/id-mapping/components/results/IDMappingResult.tsx, src/uniprotkb/utils/resultsUtils.ts
Get column sorting in ID mapping results working
https://www.ebi.ac.uk/panda/jira/browse/TRM-27602
(Peptide search sorting doesn't work because the accessions endpoint doesn't currently support this but I'm about to write a jira for this)
- When updating column sort use `history.location.pathname` rather than the corresponding `SearchResultsLocations[namespace]`
- Add `sort` param to ID mapping results API request
Manual
=> Add sorting to ID mapping results.

src/shared/hooks/useMatchWithRedirect.ts, src/tools/align/components/results/AlignResult.tsx, src/tools/blast/components/results/BlastResult.tsx, src/tools/id-mapping/components/results/IDMappingResult.tsx, src/tools/peptide-search/components/results/PeptideSearchResult.tsx, src/uniparc/components/entry/Entry.tsx, src/uniprotkb/components/entry/Entry.tsx
generalise the use of useMatchWithRedirect to entry pages too, and redirect any non-valid tab value to a default subPage instead of crashing
Change the hook to cover more use cases, use it in more places
Go edit the "subpage" section of the URL for any tool or UniProtKB or UniParc entry pages to either remove it completely or invent something invalid.
This is really an edge-case for if a user edits the URL to at least point to something useful AND in the case of UniProtKB entry in the case where the user followed a now invalid URL (like https://www.uniprot.org/uniprot/P05067/protvista)
=> generalise the use of useMatchWithRedirect

src/shared/hooks/useDataApi.ts, src/shared/utils/fetchData.ts, src/tools/peptide-search/components/results/PeptideSearchResult.tsx, src/tools/state/getCheckJobStatus.ts
There is an issue at:
https://beta.uniprot.org/peptide-search/PM20220323d25f892452724e5db0ac67d571484bc9
where we are asking for json from the peptide search endpoint but text is returned instead and so causes a json parsing error.
- Request text in the header
- Remove redundant headers from `fetchData` args
- Use a ref for options in `useDataApi` to prevent the useEffect continually re-firing
TODO: tests need fixing because of a lodash-es issue.
=> Use data api options

src/shared/__test-helpers__/customRenderHook.tsx, src/tools/hooks/__tests__/useInitialFormParameters.spec.tsx, src/tools/hooks/useInitialFormParameters.ts, src/tools/hooks/useInitialFormParameters.tsx
Generic approach to load any form field data from the URL (similar way as we do currently with accession). Works with Peptide Search's server params with the exception of taxonomy. Created [jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-27685) for validation more generally.
- Iterate through all default values and look first for url params, then state values, and finally use default if neither of these are there
- Alignment forms:
- Check if the user is at an alignment location before fetching accessions
- Dispatch message if user provides both ids and sequence in 
Added more unit tests
=> 2022 05 did you mean url params

src/shared/components/results/DidYouMean.tsx
Show version-less uniparc suggestion if user searched with a version.
- Use a regex to make sure it's an upid with version
- Only add suggestion if not returned in results already
- Make key more specific as duplicate key warning still being observed. To reproduce (on commit before [0c26595](https://github.com/ebi-uniprot/uniprot-website/pull/593/commits/0c265955ebaf2a7c8ef44a854f9347bee1278bb4)):
1. http://localhost:8080/uniparc?query=p05067.3
2. (click on the uniprotkb suggestion)
3. http://localhost:8080/uniprotkb?query=p05067.3
None
=> Add UniParc version-less suggestion (if not already there).

src/shared/components/results/__tests__/__snapshots__/ResultsData.spec.tsx.snap, src/uniparc/types/entrySection.ts, src/uniprotkb/adapters/generatePageTitle.ts, src/uniprotkb/components/entry/Entry.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/results/__tests__/__snapshots__/UniProtKBCard.spec.tsx.snap, src/uniprotkb/types/entrySection.ts
Use `_` convention for anchor links for consistency with pre-5/22 website. [Jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-27782)
- Updated all `EntrySection` enums so that the anchors now use `_` convention
- Used the enums in a few places where we just used text
=> Entry section anchors

src/shared/components/entry/EntryDownload.tsx, src/uniparc/components/entry/Entry.tsx, src/uniref/components/entry/Entry.tsx
Temporarily warn users when downloading uniref members or uniparc xrefs.
Jiras
- https://www.ebi.ac.uk/panda/jira/browse/TRM-27679
- https://www.ebi.ac.uk/panda/jira/browse/TRM-27680
Dispatch messages with choices
None
=> No stream warnings

src/supporting-data/taxonomy/components/entry/ChildNavigation.tsx, src/supporting-data/taxonomy/components/entry/Entry.tsx, src/supporting-data/taxonomy/components/entry/__tests__/ChildNavigation.spec.tsx, src/supporting-data/taxonomy/components/entry/__tests__/__snapshots__/ChildNavigation.spec.tsx.snap, src/supporting-data/taxonomy/components/entry/styles/child-navigation.module.css
Taxonomy entry children navigation https://www.ebi.ac.uk/panda/jira/browse/TRM-27018
Since we're not going to get all direct children in the initial payload, I opted to use the navigation as a "preview" of the corresponding search. Make it look like the ExpandableList component, but one will expand to the corresponding taxonomy search for either the direct children (through a "parent" search) or all the descendants (through an "ancestor" search)
Added a test for the new ChildNavigation component
=> add taxonomy navigation through search page

src/uniprotkb/adapters/sectionConverter.ts, src/uniprotkb/components/entry/DiseaseAndDrugsSection.tsx, src/uniprotkb/components/entry/__tests__/EntryMain.spec.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/DiseaseInvolvementView.tsx, src/uniprotkb/components/protein-data-views/VariationView.tsx, src/uniprotkb/components/protein-data-views/__tests__/VariationView.spec.tsx, src/uniprotkb/components/protein-data-views/__tests__/__mocks__/diseaseInvolvementUIData.ts, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/DiseaseInvolvementView.spec.tsx.snap, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/VariationView.spec.tsx.snap, src/uniprotkb/config/UniProtKBColumnConfiguration.tsx, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap, src/uniprotkb/types/commentTypes.ts
Add variations from UniProt website API (as opposed to the Proteins API) right below the related diseases
Merge the "Natural Variants" with their corresponding diseases using the description as a key to match against the disease "acronym". Display a table below the disease.
Move the section with all the variations in a lazy loader in order to save the Proteins API network call (which can be used) and the corresponding rendering. This has the consequence of disabling the ctrl-f feature for this area (until the user scrolls to it) but ctrl-f is still available for UniProt-curated variations associated with a disease.
Note that not all "Natural Variants" have a disease associated with them, so they can't be linked to a disease.
Updated mocks and snapshots
=> 2022 06 variants in diseases

src/shared/components/results/Results.tsx, src/shared/hooks/usePagination.ts
add error and status return values from usePagination in order to show an error when the API returns an error
usePagination was not exposing any error or status, so expose them in order to be able to use them to show the appropriate error message.
This will show the error message if there is an error while loading the 1st page.
Note that this will surface the error and status of the current page being loaded, but the added condition of checking if there are results in the array should prevent replacing the already loaded data in the event of one of the subsequence page load failing. At the moment this is not handled I believe, and I'm assuming it would either show the Loader component forever or just stop adding to the list as if all results were shown. @dlrice if you want to have a go at …
=> ErrorComponent in results page

src/proteomes/components/entry/Components.tsx, src/proteomes/components/entry/ComponentsButtons.tsx, src/proteomes/components/entry/Entry.tsx, src/proteomes/components/entry/Overview.tsx, src/proteomes/components/entry/__tests__/Components.spec.tsx, src/proteomes/components/entry/__tests__/ComponentsButtons.spec.tsx, src/proteomes/config/ProteomesEntryConfig.tsx, src/proteomes/config/download.ts, src/shared/components/download/Download.tsx, src/supporting-data/diseases/components/entry/Entry.tsx
- Missing fields in proteome entry such as strain and the replacement proteome info for redundant proteome are added.
- The keywords field in diseases are exposed too.
- The download format for Redundant proteomes is set to only FASTA like in the current website.
Added an optional property 'supportedFileFormats' in Download component to allow exceptions.
Below tests were changed to reflect the latest changes
- src/proteomes/components/entry/__tests__/Components.spec.tsx
- src/proteomes/components/entry/__tests__/ComponentsButtons.spec.tsx
=> Missing data

src/shared/hooks/__tests__/useItemSelect.spec.ts, src/shared/hooks/__tests__/useJobFromUrl.spec.tsx, src/shared/hooks/useItemSelect.ts, src/tools/blast/components/results/BlastResult.tsx, src/tools/hooks/__tests__/useInitialFormParameters.spec.tsx
Fix entries getting "stuck" in table selection after the content of the table has changed https://www.ebi.ac.uk/panda/jira/browse/TRM-26979
Given that a table content change is correlated with a URL location change, listen to that in order to empty/reset the list of entries.
Some tables go through a "stale" state then display a subset of the previous content (e.g.: BLAST results facets), for these cases, the hook will try to reuse the checkboxes that are currently rendered and checked in order to keep them in the list of selected entries, but will only do so after the optional "loading" flag passed to it is set to false.
Manual tests + updated existing tests to not fail because of the new dependency to the global location state
=> 2022 08 row selection fix

src/shared/components/download/DownloadAPIURL.tsx
Discussing with @LeonardoGonzales that through testing having a batch size of 500 is much quicker for the users:
```
Query:NOD2 HUMAN (n=1109)
25 4.5s
100 2.1s
500 1.3s
==========
Query:organism_id:2697049 (n=7042)
25 25.8s
100 14.8s
500 11.7s
==========
Query:organism_id:9606 (n=204907)
25 1305.8s
100 862.5s
500 649.3s
```
so this should be set when providing the pagination/search API URL.
Updated the DownloadAPIURL component to have a batch size of 500.
None
=> Use 500 for chunk size in API pagination url.

index.html, src/app/components/home-page/HomePage.tsx, src/index.tsx, src/shared/components/HTMLHead.tsx, src/shared/components/results/Results.tsx
Try to get more accurate page view values and better tracking in general
Rely on a mutation observer to check when the page changes. When the page is loaded, a data attribute is changed to declare that the page is loaded and can be tracked, and make sure to not duplicate measurements by checking the href did change. Deactivate any kind of automatic logging from gtag, all is handled manually in our code.
Manual testing, console.log betweek lines 53 and 54 of file `src/index.tsx`.
Check for correct number of logs on:
- Initial pages vs website navigation
- Result pages
- Entry pages and subpages
- Tool result pages and subpages
- Home page
- Common redirects (/uniprot/<accession> -> /uniprotkb/<accession>/entry should log once)
=> apply some of the points discussed for better page tracking

src/app/components/home-page/AnalysisTools.tsx, src/app/components/home-page/__tests__/__snapshots__/NonCritical.spec.tsx.snap, src/app/components/home-page/styles/non-critical.module.scss, src/shared/components/action-buttons/AddToBasket.tsx, src/shared/components/action-buttons/ToolsButton.tsx, src/shared/components/entry/__tests__/__snapshots__/SequenceView.spec.tsx.snap, src/shared/components/layouts/SecondaryItems.tsx, src/shared/components/layouts/UniProtFooter.tsx, src/shared/components/layouts/UniProtHeader.tsx, src/shared/components/layouts/__tests__/__snapshots__/UniProtFooter.spec.tsx.snap, src/shared/components/layouts/styles/footer.module.scss, src/shared/components/layouts/styles/secondary-items.module.scss, src/shared/components/layouts/styles/single-column-layout.scss, src/shared/components/layouts/styles/uniprot-header.module.scss, src/shared/components/results/ResultsData.tsx, src/shared/components/search/SearchContainer.tsx, src/shared/hooks/useMatchMedia.ts, src/shared/styles/helper.module.scss, src/tools/peptide-search/components/results/__tests__/__snapshots__/PeptideSearchResult.spec.tsx.snap, src/uniprotkb/components/entry/ComputationallyMappedSequences.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/ComputationallyMappedSequences.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/UniProtKBFeaturesView.tsx, src/uniref/components/entry/MembersSection.tsx
disable all tools and basket references in mobile view https://www.ebi.ac.uk/panda/jira/browse/TRM-28221
Use of media query, as defined in Franklin, in 2 ways:
- Use directly in CSS through mixin
- Use in JavaScript
Create abstraction for both ways and try to reused wherever possible
Manual testing on narrow screen + updated snapshots
=> hide all references to tools and basket in mobile view

src/basket/BasketFullView.tsx, src/basket/BasketMiniView.tsx, src/shared/components/results/AccessionView.tsx, src/shared/components/results/ResultsButtons.tsx, src/shared/components/results/__tests__/AccessionView.spec.tsx, src/shared/components/results/__tests__/__snapshots__/AccessionView.spec.tsx.snap, src/tools/utils/urls.ts, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/UniProtKBFeaturesView.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/FeaturesView.spec.tsx.snap, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Add basket button for features spanning >1 amino acid along with the existing BLAST button
The modifications subset is stores as a string in the Basket.
A Map of subset to accession is passed to `ResultsButton` to deal with exceptions like ID mapping and Download functions.
Additional test added to AccessionView to see how the ids with ranges are shown
Other snapshots updated with the Add Basket button
=> 2022 09 add basket to subsets

src/shared/components/views/FeaturesView.tsx, src/tools/utils/feature.ts, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/UniProtKBFeaturesView.tsx, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Add links to search for ligand/ligandPart in uniprotkb and chebi
- `description` is now a `ReactNode` which includes these links
- slight refactoring of the table cell render
- Update snapshots
=> Ligand links

src/automatic-annotations/shared/entry/ConditionsAnnotations.tsx, src/automatic-annotations/shared/model.ts, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/LigandDescriptionView.tsx, src/uniprotkb/components/protein-data-views/UniProtKBFeaturesView.tsx, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Same ligand view was appearing in both uniprotkb and unirule which can be unified.
Create single view
Updated
=> Ligand description view

src/proteomes/components/entry/Components.tsx, src/proteomes/components/entry/__tests__/__snapshots__/Components.spec.tsx.snap, src/proteomes/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/shared/config/externalUrls.ts, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/XRefView.tsx, src/uniprotkb/config/database.ts, src/uniprotkb/utils/__tests__/__mocks__/databaseInfo.ts, src/uniprotkb/utils/__tests__/__snapshots__/database.spec.ts.snap, src/uniprotkb/utils/__tests__/xrefUtils.spec.ts, src/uniprotkb/utils/xrefUtils.ts
Fix a few xref issues:
1. GenCC & ClinGen must have as many links as there are HGNC IDs
2. GenCC & ClinGen must have HGNC IDs for URL text
3. GenCC & ClinGen must be located in Disease & Variants entry page section (as well as all xrefs tab)
Jiras for above three points:
- https://www.ebi.ac.uk/panda/jira/browse/TRM-27783
- https://www.ebi.ac.uk/panda/jira/browse/TRM-28048
4. Fix RefSeq link (https://www.ebi.ac.uk/panda/jira/browse/TRM-28297)
5. Update proteomes link to NCBI nucleotides (https://www.ebi.ac.uk/panda/jira/browse/TRM-28298)
1. Add exception to creation of implicit xref to explicitly check if GenCC & ClinGen and if so add an xref for of the HGNC IDs
2. Add exception to xref view render to handle GenCC & ClinGen case
3. Add GenCC & ClinGen to Disease & Variants section in xref …
=> xrefs: gencc, clingen, refseq, ncbi nucleotide

src/tools/config/urls.ts, src/tools/id-mapping/components/results/IDMappingResult.tsx
Fix this bug: ID mapping results table not rendering lineage column (https://www.ebi.ac.uk/panda/jira/browse/TRM-28307)
Use useColumnNames in ID mapping results to be used in creation of results url
None
=> fix: ID mapping results table not rendering lineage column

src/shared/components/download/Download.tsx, src/shared/components/results/ResultsButtons.tsx, src/tools/id-mapping/components/results/IDMappingResult.tsx
[Incorrect ID mapping download url for large uniprot jobs](https://www.ebi.ac.uk/panda/jira/browse/TRM-28328)
Pass `notCustomisable` to `Download` and condition on this to generate URL.
Just in the browser:
ID mapping 360,382 results found for EMBL-GenBank-DDBJ → UniProtKB
003cd880ca7033a5c8685b9d2376c1772ffe84bf
=> Pass notCustomisable to Download and condition on this to generate URL.

package.json, src/app/components/home-page/CoreData.tsx, src/app/components/home-page/LatestNews.tsx, src/app/components/home-page/NeedHelp.tsx, src/app/components/home-page/SupportingData.tsx, src/app/components/home-page/UniProtData.tsx, src/app/components/home-page/__tests__/__snapshots__/NonCritical.spec.tsx.snap, src/app/components/home-page/styles/non-critical.module.scss, src/shared/components/layouts/styles/contact.module.scss, src/shared/components/layouts/styles/footer.module.scss, src/shared/components/results/__tests__/__snapshots__/ResultsData.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/KeywordView.tsx, src/uniprotkb/components/protein-data-views/styles/keyword-view.module.scss, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap, yarn.lock
Mobile view for homepage https://www.ebi.ac.uk/panda/jira/browse/TRM-28225
+ fix too small click targets reported by Google Search Console
- Use new classes in franklin to define different grid layout depending on breakpoints
- Mainly: when 4 tiles, switch to 2 tiles per row on 2 rows
- Add "in-between" breakpoint for when the middle size is too tight but we don't want to trigger mobile view yet
- Refactor home page content to have a better reflow when going in mobile view
- Create new specific rules for mobile view
- Check links that were reported by Google Search Console as too small or touch target overlapping with others and adjust both size (padding, for bigger click target) and spacing between them (to avoid clicking on the wrong one with touch)
- Played with values until validated …
=> 2022 10 mobile view click targets and homepage

src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/ProteinProcessingSection.spec.tsx.snap, src/uniprotkb/components/protein-data-views/UniProtKBEvidenceTag.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/PtmExchangeEvidenceTag.spec.tsx.snap, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/UniProtEvidenceTag.spec.tsx.snap, src/uniprotkb/config/evidenceCodes.ts
Show Reviewed instead of automatic annotation evidence tag. (https://www.ebi.ac.uk/panda/jira/browse/TRM-26900)
I have added two evidence labels (legacy as reference)
UNIRULE_ANA = 'UniRule annotation', 
PROSITE_RULE = 'PROSITE-ProRule annotation'
Documentation: https://www.uniprot.org/help/evidence_table
Example entries to test: Q92824, Q9D659, W7L9E0
=> 2022 13 revise eco codes

src/tools/blast/components/results/BlastResult.tsx, src/tools/components/ResultButtons.tsx
BLAST result download issue related to the latest column customisation (https://www.ebi.ac.uk/panda/jira/browse/TRM-28740)
The previous resultdownload component(exclusively for Align and BLAST) is restored, with a minor change
- Additional customise columns button is added. 
- Toggle card/table is not applicable anyway (not included)
- As part of it, resubmit feature is back
=> fix download for BLAST results

src/uniprotkb/components/entry/GoRibbon.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/entry/styles/go-ribbon.module.scss, src/uniprotkb/components/protein-data-views/UniProtKBEvidenceTag.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/UniProtEvidenceTag.spec.tsx.snap, src/uniprotkb/config/evidenceCodes.ts
The current label 'Manual assertion' that is shown for the GO evidence tag is more UniProtKBEvidence related and is also inconsistent. https://www.ebi.ac.uk/panda/jira/browse/TRM-27775
{
manual: true/false,
label: '',
description: ''
}
From the above evidence data schema, label is used for UniProtKB related tags and description only for GO evidences. Getting rid of one is a possible solution but we don't know for sure which are common to both and not want to end up deleting a potential right one. 
=> 2022 13 revise ECO codes for GO evidence tags

src/shared/config/externalUrls.ts, src/uniprotkb/adapters/uniProtkbConverter.ts, src/uniprotkb/components/protein-data-views/DiseaseInvolvementView.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/DiseaseInvolvementView.spec.tsx.snap, src/uniprotkb/config/UniProtKBColumnConfiguration.tsx, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Display dbSNP cross references data(from FeatureCrossReferences unlike other xrefs). [JIRA](https://www.ebi.ac.uk/panda/jira/browse/TRM-28089)
Information displayed are as follows:
- Variant change with link to UniProt variant page
- rsID
- Links to dbSNP and Ensembl
Description is there in the data but left out as it started to look cluttered. I will attach screenshot for reference.
Example in Legacy for one such with extra description - https://legacy.uniprot.org/uniprot/?query=database%3A%28type%3Adbsnp%29+AND+A0A1B0GTW7&sort=score
Links to dbSNP and UniProt variant pages are added in Disease and variants section following Elisabeth's comment in the JIRA.(http://localhost:8080/uniprotkb/P78363/entry#disease_variants)
Updated the snapshots
=> 2022 14 db snp column

src/shared/components/MapTo.tsx, src/shared/components/__tests__/MapTo.spec.tsx, src/shared/components/__tests__/__snapshots__/MapTo.spec.tsx.snap, src/tools/align/components/AlignForm.tsx, src/tools/blast/components/BlastForm.tsx, src/tools/id-mapping/components/IDMappingForm.tsx, src/tools/id-mapping/components/__tests__/__snapshots__/IDMappingForm.spec.tsx.snap, src/tools/peptide-search/components/PeptideSearchForm.tsx, src/uniref/components/entry/Entry.tsx
Add the UniRef map to feature using ID Mapping [TRM-28956](https://www.ebi.ac.uk/panda/jira/browse/TRM-28956)
Refactor and reuse the "MapTo" dropdown
Prepopulate an ID mapping form with the corresponding data and the correct from/to fields
Fix and prepopulate the job name field
Refactor tools forms for consistency and for the above name prepopulation fix
Manual testing + added unit test for snapshots of links being generated
=> add map to feature to UniRef entries + change ID mapping form

src/shared/components/download/Download.tsx, src/tools/peptide-search/components/results/PeptideSearchResult.tsx
Fix peptide search download for more than 1000 matches by redirecting to ID mapping
https://www.ebi.ac.uk/panda/jira/browse/TRM-28800
A warning message with a link to ID mapping and all the things present in the download panel disabled.
=> Add warning message in download panel for more than 1000 matches

src/tools/id-mapping/types/idMappingSearchResults.ts, src/tools/state/getCheckJobStatus.ts
We are not showing the failure messages for ID mapping jobs which is provided by Backend.
https://www.ebi.ac.uk/panda/jira/browse/TRM-28947
Include the 'ErrorDescription' in the dispatch object
To review:
The error messages are not very helpful in case of error code 50
=> Show ID mapping errors returned by backend in Tools dashboard

src/query-builder/components/AutocompleteField.tsx, src/query-builder/utils/__tests__/fieldInitializer.spec.ts, src/query-builder/utils/fieldInitializer.ts
Currently [a bug](https://www.ebi.ac.uk/panda/jira/browse/TRM-28780) in the query builder where queries with autocomplete text fields eg `organism_name:human` are not being initialized correctly.
When initializing `value` and `selectedId` in `AutocompleteField` treat these differently:
- If the `queryBit` contains the `autoCompleteQueryTerm` then return this.
- Else if a name search return the normal field term (eg `organism_name`) unless `isAutoCompleteQueryId` is true in which case return an empty string.
Added two unit tests.
=> Advanced search form issue for _name / _id fields

src/basket/BasketMiniView.tsx, src/shared/components/download/Download.tsx, src/shared/components/results/ResultsButtons.tsx, src/shared/config/apiUrls.ts
[Download entire basket is affected by last search query/URL](https://www.ebi.ac.uk/panda/jira/browse/TRM-29094)
Create and use `inBasketMini` prop
None
=> Create and use inBasketMini to prevent queries etc incorrectly affecting basket downloads

package.json, src/help/config/featureTypeHelpMappings.ts, src/uniprotkb/adapters/ptmExchangeFeaturesConverter.ts, src/uniprotkb/components/entry/KineticsTableView.tsx, src/uniprotkb/components/entry/__tests__/KineticsTableView.spec.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/KineticsTableView.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/ProteinProcessingSection.spec.tsx.snap, src/uniprotkb/components/protein-data-views/FreeTextView.tsx, src/uniprotkb/components/protein-data-views/PtmExchangeEvidenceTag.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/PtmExchangeEvidenceTag.spec.tsx.snap, src/uniprotkb/types/featureType.ts, yarn.lock
Replace the table for Kcat in kinetics with free text as before. 
JIRA - https://www.ebi.ac.uk/panda/jira/browse/TRM-29086
Removed the table.
Added a condition in RichText component for handling superscript for scientific notation present in kcat constants.
Example entries to try:
A0A0B6CGH9
Q8BGC4
P04180
Updated the test.
=> Display Kcat values of Kinetics as free text

src/shared/components/download/Download.tsx, src/shared/components/download/DownloadAPIURL.tsx, src/shared/config/__tests__/ftpUrls.spec.ts, src/shared/config/ftpUrls.ts
Catch when a user is downloading reviewed:true|false, either by facets or directly from query, in specific formats - fasta, text, xml - and direct them to download this from FTP.
- Create a fn to simplify queries.
- Map simplified query to ftp filename conventions.
- Check fileformats exists at ftp
- Instruct user to download both in api urls and when clicking download button. Note this blocks stream download and async download.
Tested
=> Catch ftp download

src/tools/align/state/alignFormReducer.ts, src/tools/blast/state/blastFormReducer.ts, src/tools/id-mapping/state/idMappingFormReducer.ts, src/tools/peptide-search/components/PeptideSearchForm.tsx, src/tools/peptide-search/state/peptideSearchFormReducer.ts
- Noticed a bug with the job name setting that was in my original BLAST form reducer so fixed this along with the other reducers.
- Swapped `parsedSequences`, `peptideSequence` and `formValues[PeptideSearchFields.peps]` to reflect the original logic.
=> 2023 05 tools refactoring pr

src/shared/components/results/ResultsData.tsx, src/shared/components/results/styles/did-you-mean.module.scss, src/shared/components/results/styles/results-data.module.scss
: Search suggestion box at the bottom has too big of a header, and smaller suggestions which are difficult to read. Also when there are few results (1 or generally less than 10) from the search, the box is too close to the results table which drifts users' focus on to the box instead of actual results.
ex) https://www.uniprot.org/uniprotkb?facets=model_organism:10116&query=erbeta
: This fix balances the header and the content of the message, and adds some increased spacing between the bottom of the results table and the suggestion box
: checked on various search queries, including …
=> 'Did you mean...' search suggestion box style changes

src/app/components/App.tsx, src/supporting-data/database/components/results/__tests__/__snapshots__/DatabaseCard.spec.tsx.snap, src/supporting-data/database/config/DatabaseColumnConfiguration.tsx, src/supporting-data/database/config/__tests__/__snapshots__/DatabaseColumnConfiguration.spec.tsx.snap
Deal with situation where the results route doesn't have a `query=` url parameter or this is just blank.
https://www.ebi.ac.uk/panda/jira/browse/TRM-26268
https://www.ebi.ac.uk/panda/jira/browse/TRM-29073
Add logic within `ResultsOrLanding` to detect absence of `query=` and add this in as `query=*`.
None
=> Redirect to star search when query is nonexistent or is empty string.

src/tools/blast/state/blastFormReducer.ts, src/tools/hooks/useInitialFormParameters.tsx
When multiple accessions are selected for BLAST or Align from the tools button, the job name is always after the first sequence. When there are multiple ones entered in the form itself, they are fine. 
The recently introduced 'userSelected' property was changing the behaviour. It is been taken care of at the 'useInitialFormParameter' level for both BLAST and Align.
Also, for BLAST if there are more than one sequence, the job name is set to be empty and the submitted jobs take the respective name after submission.
=> Fix job name behaviour for BLAST and Align

src/tools/components/APIRequest.tsx, src/tools/config/urls.ts, src/tools/peptide-search/components/PeptideSearchForm.tsx, src/tools/peptide-search/components/results/PeptideSearchResult.tsx, src/tools/peptide-search/components/results/PeptideSearchResultTable.tsx, src/tools/peptide-search/components/results/__tests__/PeptideSearchResult.spec.tsx, src/tools/peptide-search/components/results/__tests__/__snapshots__/PeptideSearchResult.spec.tsx.snap, src/tools/peptide-search/types/peptideSearchFormParameters.ts, src/tools/peptide-search/types/peptideSearchServerParameters.ts, src/tools/utils/index.tsx
Use the other endpoint for Peptide search jobs. It also provides the job parameters which enables to view the inputs of a remote job.
Replace the URL and update the server parameters.
Pass the input parameters obtained where necessary instead of accessing tools state
Test updated
=> Different endpoint for peptide search

src/shared/config/externalUrls.ts, src/uniprotkb/components/protein-data-views/DiseaseInvolvementView.tsx, src/uniprotkb/components/protein-data-views/VariationView.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/DiseaseInvolvementView.spec.tsx.snap, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/VariationView.spec.tsx.snap, src/uniprotkb/config/UniProtKBColumnConfiguration.tsx, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Add ProtVar links in entry and variant-viewer tab
Link the variant change to ProtVar and VAR ids to Expasy. This also changes the link from Expasy to ProtVar in the dbSNP column of results page.
=> ProtVar links in Variation table

src/proteomes/components/entry/Components.tsx, src/proteomes/components/entry/ComponentsButtons.tsx, src/proteomes/components/entry/Overview.tsx, src/proteomes/components/entry/__tests__/Components.spec.tsx, src/proteomes/components/entry/__tests__/ComponentsButtons.spec.tsx, src/proteomes/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/proteomes/config/ProteomesEntryConfig.tsx, src/proteomes/config/download.ts, src/shared/components/download/Download.tsx, src/shared/components/download/__tests__/Download.spec.tsx, src/shared/components/download/styles/download.module.scss
Add an option to download only reviewed proteins (with isoforms) for organisms that are Eukaryote
Changed the existing downloadAll from boolean to a union of 'all, selected, reviewed'
Pass a 'showReviewedOption' flag to include in the download along with isoform statistics.
Created an additional test case
=> Proteome download

src/shared/components/download/__tests__/Download.spec.tsx, src/shared/components/results/AdvancedSearchSuggestion.tsx, src/shared/components/results/ExactFieldSuggestion.tsx, src/shared/components/results/OrganismSuggestion.tsx, src/shared/components/results/Results.tsx, src/shared/components/results/SearchSuggestions.tsx, src/shared/components/results/TaxonomyLevelsSuggestion.tsx, src/shared/components/results/__tests__/SearchSuggestions.spec.tsx
There should be no suggestions of queries which
- return 0 hits
- return the same hits as the original question.
As the search results of a suggestion are subsets of the whole search, comparing the number of hits is enough.
e.g. https://www.uniprot.org/uniprotkb?query=BSU06210 don't
suggest to restrict to gene name.
https://www.uniprot.org/uniprotkb?query=gene%3Acyk3%20AND%20organism_id%3A284812
don't suggest exact match as it is the same result
Exact match, taxonomy and matching fields suggestion takes into account the number of results to decide. if it is different to the total number of hits that are currently shown in the results page, the suggestion is shown
=> Advanced search suggestions

src/uniprotkb/components/protein-data-views/DiseaseInvolvementView.tsx, src/uniprotkb/components/protein-data-views/FreeTextView.tsx, src/uniprotkb/components/protein-data-views/__tests__/FreeTextView.spec.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/DiseaseInvolvementView.spec.tsx.snap, src/uniprotkb/utils/__tests__/index.spec.ts, src/uniprotkb/utils/index.ts
[Improve RichText component to parse variant description texts (parse dbsnp links)](https://www.ebi.ac.uk/panda/jira/browse/TRM-29431)
- Add dbsnp regexp
- Extract `getTextProcessingParts` create tests as I was messing things up but couldn't figure out why
- Made explicit capture and non-capture groups to avoid multiple regex matches
Updated and added
=> Rich text dbsnp

src/help/components/results/Results.tsx, src/shared/components/layouts/styles/sidebar-layout.module.scss
Uniprot website currently is displayed full-width, which raises readability issues in desktop/large monitor environments. 
This fix sets a max-width on the content which improves the readability of pages.
Max-width of 200 ch set for all pages minus search results. 
Tested on:
- homepage
- entry pages
- search results page
- help pages, help search result pages
- blast/align/idmapping pages and results pages
=> set max-width: 200ch on non-search result pages

src/app/components/App.tsx, src/app/components/Covid19RedirectWarning.tsx, src/app/components/DevDeploymentWarning.tsx, src/app/components/styles/dev-deployment-warning.module.scss, src/app/components/styles/warning-message.module.scss
COVID-19 portal is being shut down so alert users if they have been redirected.
Corresponds to this [traffic-manager MR](https://gitlab.ebi.ac.uk/wp/wp-traffic-manager/-/merge_requests/1175).
- Check `window.location.search` for `fromCovid19Portal=true` and if present show a dismissible message.
- Renamed the existing deployment warning for clarity.
None
=> Covid redirect warning

src/shared/components/download/Download.tsx, src/shared/components/download/__tests__/Download.spec.tsx, src/shared/components/download/__tests__/downloadUtils.spec.ts, src/shared/components/download/downloadActions.ts, src/shared/components/download/downloadReducer.ts, src/shared/components/download/downloadUtils.ts, src/tools/async-download/components/AsyncDownloadConfirmation.tsx, src/tools/async-download/components/AsyncDownloadForm.tsx, src/tools/async-download/components/__tests__/AsyncDownloadConfirmation.spec.ts, src/tools/async-download/components/__tests__/AsyncDownloadForm.tsx.spec.tsx, src/tools/async-download/components/styles/async-download-confirmation.module.scss, src/tools/async-download/state/__tests__/asyncDownloadFormReducer.spec.ts, src/tools/async-download/state/asyncDownloadFormActions.ts, src/tools/async-download/state/asyncDownloadFormReducer.ts
[Create a confirmation form when submitting a download async form to create friction.](https://www.ebi.ac.uk/panda/jira/browse/TRM-29508)
Create a new view which is triggered from the async download form
Created and updated.
=> Async download friction

src/uniprotkb/components/graphs/PieChart.tsx, src/uniprotkb/components/graphs/__tests__/PieChart.spec.ts
Redistribute the pie chart data to avoid squished labels.
Used @aurel-l's algorithm outline. I found that sorting ascended worked better.
Unit tests.
=> Distribute pie chart

src/uniprotkb/components/protein-data-views/EMBLView.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/XrefView.spec.tsx.snap, src/uniprotkb/components/protein-data-views/styles/embl-view.module.scss, src/uniprotkb/config/UniProtKBColumnConfiguration.tsx, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
[Sequence Protein Molecule Type Status: No data displayed for NOT_ANNOTATED_CDS](https://www.ebi.ac.uk/panda/jira/browse/TRM-27954)
http://localhost:8080/uniprotkb/A0A0B4J2F0/external-links
- Include situations where protein or nucleotide sequence is not available and display a `-` for this missing data.
- Use `·` to copy 3D xref table link separator style
- Update column headers per jira comments
- Noticed the `|` separator was a little unsymmetrical in the catalytic activity sections so updated the spacing
Updated
=> Embl links update

src/shared/config/apiUrls.ts, src/uniprotkb/components/statistics/AbstractSectionTable.tsx, src/uniprotkb/components/statistics/ReviewedUnreviewedStatsTable.tsx, src/uniprotkb/components/statistics/StatisticsPage.tsx, src/uniprotkb/components/statistics/StatsTable.tsx, src/uniprotkb/components/statistics/styles/statistics-page.module.scss, src/uniprotkb/components/statistics/styles/uniprotkb-labels.module.scss, src/uniprotkb/components/statistics/utils.ts
- [Statistics: add average per entry column](https://www.ebi.ac.uk/panda/jira/browse/TRM-30348)
- Remove ⮑ indent instead; fix un/reviewed icon spacing.
- Unrelatedly, remove obsolete api urls.
- Pass the number of entries for each of reviewed and unreviewed
- To make it clear to the user what the average is referring to state in the header the entry type.
None
=> Per entry average

src/shared/components/error-pages/ResourceNotFoundPage.tsx, src/shared/components/layouts/ReleaseInfo.tsx, src/shared/components/layouts/UniProtFooter.tsx, src/shared/components/layouts/__tests__/__snapshots__/UniProtFooter.spec.tsx.snap, src/tools/peptide-search/components/results/__tests__/__snapshots__/PeptideSearchResult.spec.tsx.snap, src/uniprotkb/components/landing-page/LandingPage.tsx, src/uniprotkb/components/statistics/StatisticsPage.tsx
[Make the statistics page public](https://www.ebi.ac.uk/panda/jira/browse/TRM-30365):
=> Link to new release statistics

src/tools/align/components/AlignForm.tsx, src/tools/align/state/__tests__/alignFormReducer.spec.ts, src/tools/align/state/alignFormActions.ts, src/tools/align/state/alignFormReducer.ts, src/tools/blast/components/BlastForm.tsx, src/tools/blast/state/__test__/blastFormReducer.spec.ts, src/tools/blast/state/blastFormActions.ts, src/tools/blast/state/blastFormReducer.ts, src/tools/id-mapping/components/IDMappingForm.tsx, src/tools/id-mapping/state/__tests__/idMappingFormReducer.spec.ts, src/tools/id-mapping/state/idMappingFormActions.ts, src/tools/id-mapping/state/idMappingFormReducer.ts, src/tools/peptide-search/components/PeptideSearchForm.tsx, src/tools/peptide-search/state/__tests__/peptideSearchFormReducer.spec.ts, src/tools/peptide-search/state/peptideSearchFormActions.ts, src/tools/peptide-search/state/peptideSearchFormReducer.ts
[Fix resubmitting job when already in the corresponding job submission form](https://www.ebi.ac.uk/panda/jira/browse/TRM-30603)
`useReducer` doesn't recreate the state if a new initial state is provided so use a `useEffect` hook to do this for us.
Add new unit tests.
=> Tools resubmit from dashboard

src/uniprotkb/adapters/sequenceConverter.ts, src/uniprotkb/config/UniProtKBColumnConfiguration.tsx
It has been [highlighted](https://www.ebi.ac.uk/panda/jira/browse/TRM-30606) that fragments are incorrectly showing precursor information.
As we are guaranteed the string format by the API just use a `split(',')[0]` to remove precursor if present for both search results and the entry page.
Manually looked at the provided examples from the [jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-30606)
| Localhost                                      | SIB                                          | Combination               | 
| ---------------------------------------------- | -------------------------------------------- | ------------------------- |
| http://localhost:8080/uniprot/P14431#sequences | http://sp.sib.swiss/uniprot/P14431#sequences | fragment, precursor       |
| …
=> Fragment fix

src/shared/components/results/ResultsFacets.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-30785
Using the isExact property of UseRouteMatch to check if the URL is the same.
For taxonomy facet showing up in Publications, 'subPage' is checked.
=> Show groupBy and taxonomy facets only in search results of UniProtKB

src/proteomes/components/entry/Components.tsx, src/proteomes/components/entry/ComponentsButtons.tsx, src/proteomes/components/entry/ComponentsDownload.tsx, src/proteomes/components/entry/__tests__/Components.spec.tsx, src/proteomes/components/entry/__tests__/ComponentsButtons.spec.tsx, src/proteomes/components/entry/__tests__/ComponentsDownload.spec.tsx, src/proteomes/config/ProteomesColumnConfiguration.tsx, src/proteomes/config/ProteomesEntryConfig.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-31017
Use Uniparc search for both redundant and excluded proteomes.
Since there is a mismatch in the counts returned in the data (JIRA linked), it is decided to not show the numbers in the download panel until it is fixed.
Added a test
=> Fix download for redundant and excluded proteomes

src/automatic-annotations/shared/entry/ConditionsAnnotations.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-30816
Add property property. Documentation reference (from Vishal): https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?spaceKey=UniProt&title=UniRule+tool+-+user+manual
I tried to find more help in the manual to link but there is nothing on proteome property.
=> Add proteome property to Unirule's rule set

src/basket/BasketFullView.tsx, src/basket/BasketMiniView.tsx, src/shared/components/download/Download.tsx, src/shared/components/download/__tests__/downloadUtils.spec.ts, src/shared/components/download/downloadUtils.ts, src/shared/components/results/ResultsButtons.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-30836
If 'SubsequencetoAccessionMap' is present, the accessions are either taken with or without subsequence depending on the selected file format.
The download/preview count and the number of entries in the basket page are all in sync now. 
Removed `notCustomisable` from BasketMiniView and used the 'inBasketMini' to determine the position of sliding panel in BasketMiniView. This also fixes the count of `selected` and `all` when downloaded from basketMiniView instead of fixed total number which is wrong.
Added a test for subsequence download from basket
=> FASTA subsequence download in Basket

package.json, src/shared/components/download/DownloadPreview.tsx, src/shared/components/entry/EntryDownload.tsx, src/shared/components/entry/EntryDownloadPanel.tsx, src/shared/components/views/FeaturesView.tsx, src/shared/config/externalUrls.ts, src/shared/config/resultsDownload.ts, src/shared/types/resultsDownload.ts, src/uniprotkb/components/entry/Entry.tsx, src/uniprotkb/components/entry/tabs/FeatureViewer.tsx, src/uniprotkb/components/entry/tabs/variation-viewer/VariationViewer.tsx
[Add more download sources for the feature viewer download panel](https://www.ebi.ac.uk/panda/jira/browse/TRM-31104)
- Show interpro representative domains if present
- Download alphafold from prediction endpoint eg https://alphafold.ebi.ac.uk/api/prediction/P05067
- Grab the urls from the json
- Modify the cif url to get confidence url
- Pass uniprot sequence to entry download to compare to alphafold's and if different don't offer downloads
- Display alphafold files in both main, variant viewer and feature viewer tab (as we do with the other additional file formats)
None
=> More feature tab downloads

src/contact/adapters/__tests__/__snapshots__/contactFormAdapter.spec.tsx.snap, src/contact/adapters/contactFormAdapter.ts, src/contact/components/ContactForm.tsx, src/contact/components/__tests__/ContactForm.spec.tsx, src/contact/components/__tests__/__snapshots__/ContactForm.spec.tsx.snap, src/contact/components/styles/contact-form.module.scss, src/tools/dashboard/components/Row.tsx
Improve contact form
- When stringifying values from jobs, make sure that objects (e.g. taxonomy) are stringified properly to avoid `[Object object]' in the message
-  Display in a read-only field all the job context that will be sent to the helpdesk:
- Avoid user modifying it
- Can enforce having the user add some context
- Add to that new visible field other information that we were including that might not have been clear to a user that it was shared with us, better for privacy
Manual check from failed job (align 2 sequences with same ID), home page, and entry page entry feedback link
=> improve contact form

src/proteomes/components/entry/ComponentsButtons.tsx, src/proteomes/components/entry/ComponentsDownload.tsx, src/shared/components/action-buttons/CustomiseButton.tsx, src/shared/components/download/Download.tsx, src/shared/components/entry/EntryDownload.tsx, src/shared/components/entry/EntryDownloadPanel.tsx, src/shared/components/results/ResultsButtons.tsx, src/shared/components/results/TaxonomyFacet.tsx, src/shared/components/search/SearchContainer.tsx, src/tools/async-download/components/AsyncDownloadConfirmation.tsx, src/tools/async-download/components/styles/async-download-confirmation.module.scss, src/uniprotkb/components/entry/tabs/history/History.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-31837
Added warning in the second step of Async download.
Added contextual help links for column customisation, download, advance search wherever applicable.
=> Add warning message in Async download for heavy queries

src/shared/components/download/__tests__/downloadUtils.spec.ts, src/shared/components/download/downloadUtils.ts
[Remove embeddings download option from ID mapping results](https://www.ebi.ac.uk/panda/jira/browse/TRM-32084)
Adjust logic
Updated
=> No idmapping embeddings download

src/app/components/styles/app.scss, src/automatic-annotations/shared/entry/ConditionsAnnotations.tsx, src/shared/components/table/styles/table.module.scss, src/shared/config/externalUrls.ts, src/shared/utils/__tests__/utils.spec.ts, src/shared/utils/utils.tsx, src/uniprotkb/components/entry/CommunityAnnotationLink.tsx, src/uniprotkb/components/entry/CommunityCuration.tsx, src/uniprotkb/components/entry/NamesAndTaxonomySection.tsx, src/uniprotkb/components/entry/SubcellularLocationSection.tsx, src/uniprotkb/components/entry/__tests__/CommunityAnnotationLink.spec.tsx, src/uniprotkb/components/entry/__tests__/CommunityCuration.spec.tsx, src/uniprotkb/components/entry/__tests__/__mocks__/communityCurationData.ts, src/uniprotkb/components/entry/__tests__/__snapshots__/CommunityAnnotationLink.spec.tsx.snap, src/uniprotkb/components/entry/__tests__/__snapshots__/CommunityCuration.spec.tsx.snap, src/uniprotkb/components/entry/styles/community-curation.module.scss, src/uniprotkb/config/UniProtKBColumnConfiguration.tsx
[Jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-31447)
- Exclude community names already existing in the curated names
- Group all community annotations by annotation
- Use a table to display community annotations, copy existing Table styles
Updated and added unit test for new util fn.
=> Community annotation

src/shared/contexts/AFDBOutOfSync.tsx, src/uniprotkb/components/entry/Entry.tsx, src/uniprotkb/components/entry/EntryMain.tsx, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/AFDBOutOfSync.tsx, src/uniprotkb/components/protein-data-views/StructureView.tsx, src/uniprotkb/components/protein-data-views/XRefView.tsx, src/uniprotkb/components/protein-data-views/styles/structure-view.module.css
Add warning message as per email thread `AlphaFold "banner" for sequences changed since AlphaFold2`. Wording following the suggested one. Approach based, as suggested, on cutoff date (so if there's a new release, we will need to update the hardcoded value)
Add franklin warning message next to the xrefs (in structure section, both in entry tab and external links tab).
Add franklin warning message above the structure viewer only when the AF model is selected: requires CSS [`:has()`](https://caniuse.com/css-has), so if not supported just don't display the message at all)
Use react context to pass the out-of-sync info as the needed info was too far away within the tree of components.
Manual checks, used P05067 for still valid model, and O75319 for out of sync one.
=> Add warning message for out of sync AF models

src/uniparc/components/sub-entry/SubEntrySimilarProteinsTabContent.tsx, src/uniprotkb/adapters/__tests__/extractIsoformsConverter.spec.ts, src/uniprotkb/adapters/extractIsoformsConverter.ts, src/uniprotkb/adapters/uniProtkbConverter.ts, src/uniprotkb/components/entry/similar-proteins/SimilarProteins.tsx, src/uniprotkb/components/entry/similar-proteins/SimilarProteinsSection.tsx, src/uniprotkb/components/entry/similar-proteins/SimilarProteinsTabContent.tsx, src/uniprotkb/components/entry/similar-proteins/SimilarProteinsTable.tsx, src/uniprotkb/components/entry/similar-proteins/__tests__/SimilarProteins.spec.tsx, src/uniprotkb/components/entry/similar-proteins/__tests__/__snapshots__/SimilarProteins.spec.tsx.snap, src/uniprotkb/config/UniProtEntryConfig.tsx
[TRM-32261](https://www.ebi.ac.uk/panda/jira/browse/TRM-32261) Fix issue when displaying similar proteins in the corresponding UniProtKB section when the canonical isoform is not `-1`
Note: no way to query the canonical isoform from the UniRef endpoint with the `-<number`.
Changed UniProtKB converter and passed the information about which of the isoforms is the canonical one, in order to query the UniRef API with the entry accession instead of the isoform accession (with `-<number`).
Also, reduce the size of the requested payloads
Haven't changed the similar proteins logic for the UniParc xref pages (UniProtKB-like) as we would need to adjust the logic to the new UniParc API first anyway.
Updated tests
Manual checks with:
- P05067 (multiple isoforms, `-1` is canonical)
- Q96G97 (multiple …
=> fix issue when canonical is not -1, also improve network usage

src/contact/components/ContactForm.tsx, src/shared/components/results/DidYouMean.tsx, src/shared/components/results/styles/did-you-mean.module.scss, src/shared/utils/translatedWebsite.ts
Better messaging when users use the website translated by a tool
Handles translation in-browser for Chrome and Firefox, as well as the Immersive Translate browser add-on (used by many of our users as seen in hotjar feedback).
- Detect changes to the html in order to check if the website is translated
- Add that info to RT tickets as context
- Add a specific message when no results are found to handle the possibility that the user might have been searching in their language
Also:
- I noticed that search suggestions were translated (the link text, not the URL), so disabled the translation for these links to avoid misleading users.
- Simplified the HTML structure of the no results message
Manual tests
=> detect translated website and add message and context

package.json, src/shared/components/table/Table.tsx, src/shared/components/table/TableFromData.tsx, src/shared/components/views/FeaturesView.tsx, src/shared/components/views/VisualFeaturesView.tsx
- Navigate on row click/expand
- Don't navigate on expand all
- Implement desired logic from ux testing:
```
if expanded:
onclick:
if highlighted:
collapse
unhighlight
else:
highlight
else:
onclick:
highlight
expand
```
None
=> More feature track table improvements

src/shared/utils/styles/tooltip.module.scss
[Remove inline styles from protvista-uniprot](https://embl.atlassian.net/browse/TRM-32372)
Needs this https://github.com/ebi-webcomponents/protvista-uniprot/pull/80 to be linked.
Added a few more styles for the stylesheet
None
=> Update protvista-tooltip styles.

src/uniprotkb/adapters/slimming/GORibbonHandler.ts, src/uniprotkb/components/entry/GoRibbon.tsx
[Expose and use new QuickGO API info about subsets](https://embl.atlassian.net/browse/TRM-32386)
- Move slimming set selection state into useGOData custom hook.
- Upon initial load, traverse entry lineage backwards to try to find more specific taxons first.
- Move quick go link below table.
None
=> Ribbon selection

src/uniprotkb/adapters/functionConverter.ts, src/uniprotkb/adapters/slimming/GORibbonHandler.ts, src/uniprotkb/adapters/slimming/__tests__/__mocks__/uniprotkbGroupedGoTerms.ts, src/uniprotkb/adapters/slimming/__tests__/__snapshots__/GoRibbonHandler.spec.ts.snap, src/uniprotkb/components/protein-data-views/SubcellularLocationGOView.tsx
[TRM-32733](https://embl.atlassian.net/browse/TRM-32733) Remove subcell GO annotations from ribbon and table in Function section
In the function section adapter, remove any cellular component related GO term, also for the GO ribbon remove any GO term from the slimming sets in order to not display that at all in the ribbon.
These GO terms are already in the subcell location section, in the GO annotations tab. That being said, I noticed the evidences were not correctly displayed, so that has been added too (now displays publications)
Updated snapshots + manual testing (mainly with P05067)
=> remove cellular component go terms from function section

src/jobs/id-mapping/components/IDMappingForm.tsx, src/jobs/id-mapping/components/__tests__/__snapshots__/IDMappingForm.spec.tsx.snap, src/jobs/peptide-search/components/PeptideSearchForm.tsx, src/jobs/peptide-search/components/__tests__/__snapshots__/PeptideSearchForm.spec.tsx.snap
Adding contextual help to ID mapping and peptide search tools
Created respective help documents and linked them to the title of each page
n/a
=> add help i's to title in pep search, idmap

src/shared/components/download/Download.tsx, src/shared/components/download/downloadUtils.ts, src/shared/config/apiUrls/results.ts
https://embl.atlassian.net/browse/TRM-32465
Show additional header option if FASTA is selected for uniparc entries with protoeme id in the query in download panel.
Add a link in the overview page of proteome.
Add link to documentation
Added new tests for util function, selection behaviour and search url generation.
=> Make new FASTA format available in download panel and proteome overview page

package.json, src/jobs/align/components/AlignForm.tsx, src/jobs/align/state/alignFormReducer.ts, yarn.lock
[TRM-32812](https://embl.atlassian.net/browse/TRM-32812) Invalidate Align form when using duplicate identifiers. Need to update to franklin https://github.com/ebi-uniprot/franklin-sites/pull/268 to also display the error messages from the SequenceSubmission component
Check number of unique names vs number of parsed sequence objects
Manual checks
=> handle multiple identifiers, invalidate form, and add error message

src/uniprotkb/components/protein-data-views/XRefView.tsx, src/uniprotkb/components/protein-data-views/styles/x-ref-view.module.scss
Small PR to try to indicate to users the two parts of the CARD xref.
Before:
After:
Context from @tgttunstall:
> the first xref is the direct link to the sequence in card db i.e the seq in up-kb (sp or trembl) with a 100% identity and coverage match with card sequence.
the second xref (which I understand is not a true xref) is the link to the resistance mechanism for that particular protein as part of the functional description/ontology  term.
so in this case it is that the protein renders the drug inactive (mechanism) and this inactivation leads to drug (antibiotic) resistance.
The 'real' xref is to the direct sequence in card.
=> Update CARD xref to indicate resistance mechanism.

__mocks__/rawSvgMock.js, package.json, src/jobs/blast/components/results/__tests__/__snapshots__/BlastResultTable.spec.tsx.snap, src/types/custom.d.ts, src/types/rhea-reaction-visualizer.d.ts, src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap, src/uniprotkb/components/protein-data-views/CatalyticActivityView.tsx, src/uniprotkb/components/protein-data-views/__tests__/CatalyticActivityView.spec.tsx, src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/CatalyticActivityView.spec.tsx.snap, src/uniprotkb/components/protein-data-views/styles/catalytic-activity-view.module.scss, src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap, yarn.lock
Depends upon this other PR
https://github.com/ebi-uniprot/franklin-sites/pull/269
[Implementation - update Rhea + usability improvements ](https://embl.atlassian.net/browse/TRM-32424)
Updated
=> Rhea upgrade

src/proteomes/components/entry/Entry.tsx, src/proteomes/components/landing-page/LandingPage.tsx, src/shared/components/RefProtMoveMessages.tsx, src/shared/components/results/ResultsData.tsx, src/shared/components/results/ResultsDataHeader.tsx, src/uniprotkb/components/entry/Entry.tsx
- To be merged on Friday if no further feedback received
- Will need to change endpoint refprotmove-fastapi from wwwdev when ready to be deployed
Show warnings for upcoming refprotmove.
- Collect warnings into a single file
- Use refprotmove-fastapi endpoint within UniProtKB entries only.
- Elsewhere just show static messages
None.
=> Refprotmove warnings
