ebi-uniprot/uniprot-website

- __tests__/ui/search/QueryHelper.spec.js
- src/ui/hoc/withData.jsx
- src/ui/search/AdvancedSearch.jsx
- src/ui/search/AdvancedSearchField.jsx
- src/ui/search/QueryHelper.js
Added support for query string generation as well as test cases.
> Trm 20180 query string

- src/results/ResultsContainer.jsx
- src/results/state/actions.js
- src/results/state/initialState.js
- src/results/views/FieldToViewMappings.jsx
- src/results/views/NameView.jsx
- src/results/views/SimpleView.jsx
- src/results/views/__tests__/FieldToViewMappings.spec.jsx
- src/results/views/__tests__/NameView.spec.jsx
- src/results/views/__tests__/SimpleView.spec.jsx
- src/results/views/__tests__/__snapshots__/FieldToViewMappings.spec.jsx.snap
- src/results/views/__tests__/__snapshots__/NameView.spec.jsx.snap
- src/results/views/__tests__/__snapshots__/SimpleView.spec.jsx.snap
- src/utils/apiUrls.js
Adding basic default views for Results table columns.
> Trm 21051 default columns

- .travis.yml
- package.json
- src/info/InfoMappings.tsx
- src/info/UniProtKBInfo.tsx
- src/layout/SideBarLayout.tsx
- src/layout/styles/SideBarLayout.scss
- src/results/ResultsContainer.tsx
- src/results/__tests__/ResultsContainer.spec.tsx
- src/results/__tests__/__snapshots__/ResultsTable.spec.tsx.snap
- src/search/state/initialState.ts
- src/search/types/searchTypes.ts
Use the page intro pattern, creating a generic system which allows us to define the content based on namespace.
> Page intro

- .travis.yml
- src/components/AutocompleteWrapper.tsx
- src/components/__tests__/AutocompleteWrapper.spec.tsx
- src/components/__tests__/__snapshots__/AutocompleteWrapper.spec.tsx.snap
- src/search/ClauseList.tsx
- src/search/Field.tsx
- yarn.lock
Update input value as user types on fields with the suggester API so user doesn't have to press enter.
> Trm 21654 autocomplete without choice fix (MERGE THIS ONE FIRST PLZ)

- .travis.yml
- src/components/__tests__/__snapshots__/AutocompleteWrapper.spec.tsx.snap
- src/components/__tests__/__snapshots__/UniProtEvidenceTag.spec.tsx.snap
- src/model/__tests__/__snapshots__/CatalyticActivity.spec.tsx.snap
- src/model/__tests__/__snapshots__/ColumnConfiguration.spec.tsx.snap
- src/model/__tests__/__snapshots__/FreeText.spec.tsx.snap
- src/model/__tests__/__snapshots__/GeneNames.spec.tsx.snap
- src/model/__tests__/__snapshots__/NameView.spec.tsx.snap
- src/model/__tests__/__snapshots__/Organism.spec.tsx.snap
- src/model/__tests__/__snapshots__/ProteinNames.spec.tsx.snap
- src/model/__tests__/__snapshots__/ProteinOverview.spec.tsx.snap
- src/model/__tests__/__snapshots__/SequenceView.spec.tsx.snap
- src/model/__tests__/__snapshots__/SimpleView.spec.tsx.snap
- src/model/__tests__/__snapshots__/Xref.spec.tsx.snap
- src/pages/__tests__/__snapshots__/HomePage.spec.tsx.snap
- src/results/__tests__/__snapshots__/ResultsTable.spec.tsx.snap
- src/results/state/resultsActions.ts
- src/search/__tests__/__snapshots__/AdvancedSearch.spec.tsx.snap
- src/search/__tests__/__snapshots__/ClauseList.spec.tsx.snap
- src/search/__tests__/__snapshots__/EnumField.spec.tsx.snap
- src/search/__tests__/__snapshots__/EvidenceField.spec.tsx.snap
- src/search/__tests__/__snapshots__/LogicalOperator.spec.tsx.snap
- src/search/__tests__/__snapshots__/RangeField.spec.tsx.snap
- src/search/__tests__/__snapshots__/SearchContainer.spec.tsx.snap
- src/search/__tests__/__snapshots__/TextField.spec.tsx.snap
- yarn.lock
Trying to avoid the fsevents error (related issue: https://github.com/facebook/jest/issues/8069). Did the following:
```
rm yarn.lock
yarn cache clean
yarn install
```
then updated test snapshots and added some new types to pass the type checking test.
> fsevents fix

- src/model/uniprotkb/sections/SubcellularLocationConverter.ts
- src/model/uniprotkb/sections/__tests__/SubcellularLocationConverter.spec.ts
- src/view/uniprotkb/SubcellularLocationSection.tsx
- src/view/uniprotkb/UniProtEntryConfig.tsx
> Subcellular Location

- src/entry/__tests__/__snapshots__/Entry.spec.tsx.snap
- src/model/uniprotkb/SectionConverter.ts
- src/model/uniprotkb/UniProtkbConverter.ts
- src/model/uniprotkb/sections/ExpressionConverter.ts
- src/model/uniprotkb/sections/FamilyAndDomainsConverter.ts
- src/model/uniprotkb/sections/FunctionConverter.ts
- src/model/uniprotkb/sections/InteractionConverter.ts
- src/model/uniprotkb/sections/PathologyAndBiotechConverter.ts
- src/model/uniprotkb/sections/ProteinProcessingConverter.ts
- src/model/uniprotkb/sections/SubcellularLocationConverter.ts
- src/model/uniprotkb/sections/__tests__/ExpressionConverter.spec.ts
- src/model/uniprotkb/sections/__tests__/FamilyAndDomainsConverter.spec.tsx
- src/model/uniprotkb/sections/__tests__/InteractionConverter.spec.ts
- src/model/uniprotkb/sections/__tests__/PathologyAndBiotechConverter.spec.ts
- src/model/uniprotkb/sections/__tests__/SubcellularLocationConverter.spec.ts
- src/view/uniprotkb/ExpressionSection.tsx
- src/view/uniprotkb/FamilyAndDomainsSection.tsx
- src/view/uniprotkb/FunctionSection.tsx
- src/view/uniprotkb/InteractionSection.tsx
- src/view/uniprotkb/PathologyAndBiotechSection.tsx
- src/view/uniprotkb/ProteinProcessingSection.tsx
- src/view/uniprotkb/SubcellularLocationSection.tsx
- src/view/uniprotkb/components/DiseaseInvolvementView.tsx
- src/view/uniprotkb/components/SequenceView.tsx
Don't got one.
No but I'm going to look into it.
> Extract common code from converters

- src/entry/__tests__/__snapshots__/Entry.spec.tsx.snap
- src/view/uniprotkb/components/GeneNamesView.tsx
- src/view/uniprotkb/components/KeywordView.tsx
- src/view/uniprotkb/components/UniProtCard.tsx
- src/view/uniprotkb/components/__tests__/__snapshots__/KeywordView.spec.tsx.snap
- src/view/uniprotkb/components/__tests__/__snapshots__/UniProtCard.spec.tsx.snap
https://www.ebi.ac.uk/panda/jira/browse/TRM-22668 - see comments on Jira
Only changed snapshots
> Update keyword component

- src/utils/__tests__/utils.spec.ts
- src/utils/utils.ts
- src/view/uniprotkb/components/GeneNamesView.tsx
- src/view/uniprotkb/components/UniProtCard.tsx
- src/view/uniprotkb/components/__tests__/__snapshots__/UniProtCard.spec.tsx.snap
https://www.ebi.ac.uk/panda/jira/browse/TRM-22899
Any card section
No
Yes
> Trm 22899 flat card with function

- src/search/utils/QueryStringGenerator.ts
- src/search/utils/__fixtures__/clauseQueryTestData.ts
- src/search/utils/__tests__/QueryStringGenerator.spec.ts
https://www.ebi.ac.uk/panda/jira/browse/TRM-22877
94.2% coverage
Generate a query where the input value has spaces.
N/A
N/A
> Trm 22877 double quote query

- src/components/AutocompleteWrapper.tsx
- src/components/__tests__/AutocompleteWrapper.spec.tsx
- src/components/__tests__/__snapshots__/AutocompleteWrapper.spec.tsx.snap
https://www.ebi.ac.uk/panda/jira/browse/TRM-22920
86.21%
Advanced search / query builder
N/A
N/A
> Trm 21903 suggester 3 chars min

- src/search/utils/QueryStringGenerator.ts
- src/search/utils/__fixtures__/clauseQueryTestData.ts
https://www.ebi.ac.uk/panda/jira/browse/TRM-22884
94.74% of lines
Yes, query builder > search for embl > select "Cross-references / Sequence databases / EMBL" > enter "*" for value and click search
N/A
N/A
> Trm 22884 advanced search xref

- src/styles/go-ribbon.scss
- src/view/uniprotkb/components/GoRibbon.tsx
> Show data loading error message to user.

- src/search/AdvancedSearch.tsx
- src/search/AdvancedSearchContainer.tsx
- src/search/__tests__/AdvancedSearch.spec.tsx
- src/search/state/searchActions.ts
- src/search/state/searchReducers.ts
- src/search/types/searchTypes.ts
- src/search/utils/clause.ts
TRM-22820
No. The coverage seems to be good.
Going to the query builder page should display a few pre-loaded clauses.
No.
No.
> fixes TRM-22820: populating advance search form with pre-selected fields

- package.json
- src/types/interaction-viewer.d.ts
- src/utils/externalUrls.ts
- src/view/uniprotkb/InteractionSection.tsx
- webpack.common.js
- yarn.lock
For an example, head over to P05067
- the visualisation will be updated later (too big for some entries). On the current website this is just not displayed over a given threshold.
- the table is missing NOTE which is missing in the data. Will talk to Jie
> Add interaction visualisation and table

- package.json
- src/index.tsx
- src/results/ResultsContainer.tsx
- src/search/state/searchActions.ts
- src/search/state/searchReducers.ts
- src/state/store.tsx
- yarn.lock
https://www.ebi.ac.uk/panda/jira/browse/TRM-22666
The 'Basket' feature is not implemented yet in the website, therefore, I was not able to persist that in the section in the local storage.
Was not needed. Configuration changes.
Yes. Change the table columns via 'Customise Data' button in the search results and/or change the search results view from Card to Table and vice versa. After refreshing the page or going back to other pages e.g. home page, your settings should be remembered.
No.
No extra back-end requests were required.
> redux persistant storage with LocalStorage

- src/model/types/CommentTypes.ts
- src/view/uniprotkb/components/CatalyticActivityView.tsx
- src/view/uniprotkb/components/__tests__/CatalyticActivityView.spec.tsx
- src/view/uniprotkb/components/__tests__/__snapshots__/CatalyticActivityView.spec.tsx.snap
https://www.ebi.ac.uk/panda/jira/browse/TRM-23160
View entry page for P00729 and look at Function > Catalytic Activity
No
Yes
> Catalytic activity bug trm 23160

- src/search/state/__tests__/actions.spec.ts
- src/search/state/searchActions.ts
- src/search/state/searchReducers.ts
https://www.ebi.ac.uk/panda/jira/browse/TRM-22869
Goto query builder / advanced search and select the reviewed field and click search.
No
N/A
> Advanced search select bug trm 22869

- src/view/uniprotkb/FunctionSection.tsx
- src/view/uniprotkb/components/SubcellularLocationView.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-23379
> Fixed issue when missing data

- src/App.tsx
- src/header/UniProtHeader.tsx
- src/results/ResultsContainer.tsx
- src/search/AdvancedSearch.tsx
- src/search/AdvancedSearchContainer.tsx
- src/search/SearchContainer.tsx
- src/search/state/searchInitialState.ts
- src/search/state/searchReducers.ts
https://www.ebi.ac.uk/panda/jira/browse/TRM-23336
1. Goto query builder
2. Enter query
3. Click search
4. Push back
5. The search will still be there
6. Click search
7. Click query builder in the header
8. The query will not be there
**...to see the query in the search bar:**
9. Click search
10. Select an result
11. The query will be in the search input
n/a
n/a
> Lost query builder trm 23336

- src/entry/publications/EntryPublications.tsx
- src/entry/publications/__mocks__/entryPublicationsData.json
- src/entry/publications/__tests__/__snapshots__/EntryPublications.spec.tsx.snap
- src/literature/types/LiteratureTypes.ts
- src/model/uniprotkb/UniProtkbConverter.ts
To test, use `http://ves-hx-cb:8090` as `devPrefix` in `apiUrls.ts`
> Update after API changes

- src/model/ColumnConfiguration.tsx
- src/model/types/CommentTypes.ts
- src/model/uniprotkb/sections/SequenceConverter.ts
- src/model/uniprotkb/sections/__tests__/SequenceConverter.spec.ts
- src/view/uniprotkb/components/FeaturesView.tsx
- src/view/uniprotkb/components/SequenceView.tsx
Adding missing "differences" section to the Isoforms.
> Add Var seq

- src/results/ResultsContainer.tsx
> Add sort field map

- src/data/database.ts
- src/utils/externalUrls.ts
- src/view/uniprotkb/components/XRefView.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-23380
We have >=75% but are not testing this as the mock api model doesn't use the database.
P05067
N/A
N/A
> Additional xrefs trm 23380

- src/components/GDPR.tsx
- src/components/__tests__/GDPR.spec.tsx
- src/components/__tests__/__snapshots__/GDPR.spec.tsx.snap
- src/layout/BaseLayout.tsx
> Move GDPR component and write tests

- src/messages/types/messagesTypes.ts
- src/shared/hooks/__tests__/useDataApi.spec.ts
- src/shared/hooks/useDataApi.ts
- src/uniprotkb/components/entry/Entry.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-23974
Go to: http://localhost:8080/uniprotkb/Q14301
Make sure you see an in-page message, notifying you about the 303 redirect.
> Handle 303 redirects

- src/tools/blast/components/BlastForm.tsx
- src/tools/blast/components/SequenceSearchLoader.tsx
- src/tools/blast/components/__tests__/__snapshots__/BlastForm.spec.tsx.snap
- src/tools/blast/config/BlastFormData.ts
- src/tools/blast/types/blastServerParameters.ts
Break up form state into smaller state items.
> Refactor state

- src/tools/blast/components/results/BlastResult.tsx
- src/tools/blast/components/results/BlastResultTable.tsx
- src/tools/blast/components/results/BlastResultsButtons.tsx
- src/tools/blast/components/results/__tests__/__snapshots__/BlastResultTable.spec.tsx.snap
- src/tools/blast/components/styles/BlastResultTable.scss
- src/uniprotkb/components/results/ResultsButtons.tsx
- Button active/disabled on results page and blast page linked to selection in data table
- use DataTable component for Blast results
> Update button activity selection, use DataTable

- src/shared/components/layouts/styles/side-bar-layout.scss
- src/tools/blast/components/results/BlastResult.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-24347
This is a very minor feature.
Open a BLAST result page. Then navigate to Text Output or Tool Input tabs. You should see a grey box on the sidebar instead of the facets.
> Disabled facets

- src/tools/blast/adapters/BlastParametersAdapter.ts
- src/tools/blast/adapters/__tests__/BlastParametersAdapter.spec.ts
- src/tools/blast/components/results/BlastResult.tsx
- src/tools/blast/components/results/BlastResultsButtons.tsx
- src/tools/blast/types/blastServerParameters.ts
- src/tools/utils/getSubmitJob.ts
Go to a finished blast job, click "resubmit", you should be taken to the Blast submission form with the prefilled fields
> implement resubmit from server parameters

- src/uniprotkb/components/entry/Entry.tsx
- In an entry page, you should be able to submit a BLAST job from the action bar.
- Also, if there are isoforms, you should be able to trigger an Align job
> Action buttons on entry page

- package.json
- src/tools/blast/components/results/BlastResult.tsx
- src/tools/blast/components/results/BlastResultTable.tsx
- src/tools/blast/components/results/HSPDetailPanel.tsx
- src/types/protvista-msa.d.ts
- webpack.config.js
- yarn.lock
> Blast hsp panel

- src/tools/blast/components/results/BlastResultTable.tsx
- src/tools/blast/components/results/HSPDetailPanel.tsx
- src/tools/blast/utils/__mocks__/hspMocks.json
- src/tools/blast/utils/__tests__/hsp.spec.ts
- src/tools/blast/utils/hsp.ts
https://www.ebi.ac.uk/panda/jira/browse/TRM-24479
Various cases tested
Try with `ncbiblast-R20200803-101021-0525-65404715-np2` and `ncbiblast-R20200803-101425-0711-3041216-np2` which are some of the extreme cases. Also make sure you check the "+N more" ones for multiple hsps to the same protein.
Nope
N/A
> Hsp all cases

- src/tools/blast/components/results/BlastResultTable.tsx
- src/tools/blast/components/results/__tests__/__snapshots__/BlastResultTable.spec.tsx.snap
- src/tools/blast/components/results/styles/BlastResultTable.scss
- [ x ] What is the link to the Jira that this PR is for?
Jira is down! But it's about adding the "query" in the table header for BLAST results.
- [ x ] Have you written tests and do these have >= 75% coverage of the code that you are contributing?
- [ x ] Is it possible to visually evaluate this PR in the browser? If so, what are the steps to do this (eg specific URLs or sections)?
Try with different BLAST results
No
No
> Add query table header

- src/tools/align/adapters/__mocks__/pim1.txt
- src/tools/align/adapters/__mocks__/pim2.txt
- src/tools/align/adapters/__tests__/pim.spec.ts
- src/tools/align/adapters/phylotree.ts
- src/tools/align/adapters/pim.ts
- src/tools/align/components/results/AlignResultPIM.tsx
- src/tools/align/components/results/styles/AlignResultPIM.scss
- src/tools/align/types/alignResults.ts
- src/tools/align/utils/__tests__/extractAccession.spec.ts
- src/tools/align/utils/__tests__/getExponentialContrast.spec.ts
- src/tools/align/utils/extractAccession.ts
- src/tools/align/utils/getExponentialContrast.ts
- did tests for the adapter and utility functions
- navigate to a percent identity matrix tab within an align result
- `no-continue`
- `react/no-array-index-key` (but working with a matrix it's the only way to identify a cell)
Implement Percent Identity Matrix (PIM):
- pim format parser from server-returned string
- parser to extract a UniProt accession from a sequence name within a job result
- visual rendering of the matrix values with a scale of colours to represent identity
> Align parsers

- src/uniref/adapters/uniRefConverter.ts
Just some basic uniref entry types
> Uniref types

- src/tools/blast/components/results/__tests__/__snapshots__/HSPDetailPanel.spec.tsx.snap
- src/tools/components/AlignmentView.tsx
Rushed PR, sorry about that.
New selection of annotations per chain
> 2020 12  possible annotation dropdown

- package.json
- src/query-builder/components/__tests__/__snapshots__/AdvancedSearch.spec.tsx.snap
- src/tools/blast/components/__tests__/__snapshots__/BlastForm.spec.tsx.snap
- src/tools/blast/components/results/BlastResultTable.tsx
- src/tools/blast/components/results/__tests__/__snapshots__/BlastResultTable.spec.tsx.snap
- src/tools/blast/components/results/styles/BlastResultTable.scss
- webpack.config.js
- yarn.lock
Depends on [https://github.com/ebi-uniprot/franklin-sites/pull/109](https://github.com/ebi-uniprot/franklin-sites/pull/109)
Now we are colouring the overview of the match in the BLAST result page, and the scoring chips, differently according to which score is visualised. Click on chip to change visualised score.
> 2020 12 alignment entry  trm 24560

- package.json
- src/shared/components/action-buttons/Align.tsx
- src/shared/components/action-buttons/Blast.tsx
- src/shared/components/entry/SequenceView.tsx
- src/shared/components/entry/__tests__/SequenceView.spec.tsx
- src/shared/components/entry/__tests__/__mocks__/sequenceUIData.json
- src/shared/components/entry/__tests__/__snapshots__/SequenceView.spec.tsx.snap
- src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
- src/uniprotkb/config/__tests__/__snapshots__/ColumnConfiguration.spec.tsx.snap
- yarn.lock
https://www.ebi.ac.uk/panda/jira/browse/TRM-23979
Check sequence section for P05067
> 2020 12 alignment entry  sequence layout

- src/shared/components/entry/EntryTitle.tsx
- src/shared/components/results/ResultsView.tsx
- src/uniref/adapters/uniRefConverter.ts
- src/uniref/components/results/UniRefCard.tsx
- src/uniref/components/results/__tests__/UniRefCard.spec.tsx
- src/uniref/components/results/__tests__/__snapshots__/UniRefCard.spec.tsx.snap
https://www.ebi.ac.uk/panda/jira/browse/TRM-25034
Added snapshot test
Search in UniRef and toggle to Card mode
> 2020 13 uniref cards

- src/uniprotkb/components/entry/ComputationallyMappedSequences.tsx
- src/uniprotkb/components/entry/__tests__/ComputationallyMappedSequences.spec.tsx
- src/uniprotkb/components/entry/__tests__/EntryPublicationsFacets.spec.tsx
- src/uniprotkb/components/entry/__tests__/__snapshots__/ComputationallyMappedSequences.spec.tsx.snap
- src/uniprotkb/components/entry/__tests__/__snapshots__/EntryPublicationsFacets.spec.tsx.snap
bug fix when data is here, but the part of the data we need to render the computationally mapped sequences is not
See example with A0A1L4BKS3
> Computationally mapped sequences bugfix

- src/shared/components/results/ResultsButtons.tsx
- src/shared/components/results/ResultsContainer.tsx
- src/shared/config/resultsDownload.ts
- src/shared/types/resultsDownload.ts
- src/uniparc/config/download.ts
https://www.ebi.ac.uk/panda/jira/browse/TRM-25178
Download components already implemented, this PR just needed UniParc's file format configuration added.
UniParc's file format configuration added.
Download components already implemented so no additional tests needed.
> UniParc download

- src/shared/components/download/Download.tsx
- src/shared/components/download/styles/download.scss
Center Loader in the download's preview dialogue.
Style changes
Style change, no test updates needed.
1. Go to an implemented namespace's Download component
2. Throttle your connection
3. Click preview to see to the Loader
> Center Loader in download preview.

- src/shared/components/layouts/SlidingPanel.tsx
- src/tools/blast/components/results/__tests__/HSPDetailPanel.spec.tsx
- src/tools/blast/components/results/__tests__/__snapshots__/HSPDetailPanel.spec.tsx.snap
The sidebar had issues with overlapping correctly over other page element. Ticket: [TRM-25297](https://www.ebi.ac.uk/panda/jira/browse/TRM-25297)
We solved the problem but using React Portals. This was not a `z-index` issue.
No new tests, but two test had to be updated to use `screen` instead.
> Sidebar overlap bug

- src/uniprotkb/components/protein-data-views/SubcellularLocationView.tsx
Ugly trick in order to inject the styles we are interested in.
I made it flexible enough so that you can add more selectors as you realise they are needed inside the shadow root.
I just put 3 selectors at the moment, but we might actually need more.
> copy and inject styles

- src/proteomes/config/download.ts
- src/shared/config/resultsDownload.ts
[Proteomes download](https://www.ebi.ac.uk/panda/jira/browse/TRM-25362)
This only requires configuration changes.
None
> Add proteomes download config.

- package.json
- src/proteomes/components/AccessionView.tsx
- src/proteomes/components/__tests__/AccessionView.spec.tsx
- src/proteomes/components/styles/accession-view.scss
- src/proteomes/config/ProteomesColumnConfiguration.tsx
- src/shared/components/entry/EntryTypeIcon.tsx
- src/uniprotkb/adapters/uniProtkbConverter.ts
- yarn.lock
Add reference proteome icon from franklin. Part of https://www.ebi.ac.uk/panda/jira/browse/TRM-25360.
Adds icon
no change
> Add reference proteome icon.

- src/shared/components/layouts/styles/side-bar-layout.scss
fix empty sidebar not showing
stretch sidebar in CSS
> fix for empty sidebar

- src/shared/components/layouts/UniProtFooter.tsx
- src/shared/components/layouts/__tests__/__snapshots__/UniProtFooter.spec.tsx.snap
- src/shared/components/layouts/styles/footer.scss
Tackle some feedback from design meeting
Change styles
Visual check
> tackle some issues in the footer

- src/shared/components/layouts/styles/base-layout.scss
- src/shared/components/layouts/styles/side-bar-layout.scss
- src/uniprotkb/components/entry/FeatureViewer.tsx
minimum spacing on page with few content [TRM-25711](https://www.ebi.ac.uk/panda/jira/browse/TRM-25711)
add minimum spacing to main section of layout
Visual check
> add minimum height for the main areas

- src/app/components/HomePageNonCritical.tsx
- src/app/components/__tests__/__snapshots__/HomePageNonCritical.spec.tsx.snap
- src/app/components/styles/home-page-non-critical.module.scss
Add spacing between homepage "hero header" sections
Added a class to add a bottom margin
Visual
> Better spacing between hero containers

- src/shared/hooks/useTextFileInput.ts
- src/shared/utils/__tests__/splitAndTidyText.spec.ts
- src/shared/utils/splitAndTidyText.ts
- src/tools/align/components/AlignForm.tsx
- src/tools/blast/components/BlastForm.tsx
- src/tools/id-mapping/components/IDMappingForm.tsx
- src/tools/id-mapping/components/__tests__/__snapshots__/IDMappingForm.spec.tsx.snap
- src/tools/id-mapping/components/style/id-mapping-form.module.scss
- src/tools/id-mapping/utils/__tests__/index.spec.ts
- src/tools/id-mapping/utils/index.ts
- src/tools/peptide-search/components/PeptideSearchForm.tsx
- src/tools/peptide-search/config/PeptideSearchFormData.ts
- src/tools/styles/ToolsForm.scss
Handle feedback post-UX meeting about peptide search form
Added a splitAndTidyText helper function
Update snapshots, new tests
> 2021 04 peptide search form feedback

- package.json
- src/messages/components/PopupMessageHub.tsx
- src/messages/components/__tests__/__snapshots__/PopupMessageHub.spec.tsx.snap
- src/messages/components/styles/popup-message-hub.scss
- src/shared/components/layouts/SlidingPanel.tsx
- src/shared/components/layouts/styles/sliding-panel.scss
- src/shared/components/results/ResultsView.tsx
- src/shared/hooks/usePagination.ts
- src/tools/blast/components/results/__tests__/__snapshots__/HSPDetailPanel.spec.tsx.snap
- yarn.lock
Extract logic to do with handling pagination
Create a custom hook
N/A
> Add pagination hook

- src/index.tsx
- src/types/webpack-define-plugin.d.ts
- webpack.config.js
Show git info for sanity check/debugging for deployed sites.
Created some new variables in webpack and console.log in index.tsx
None
> Console.log git information for build.

- src/tools/state/getCheckJobStatus.ts
- src/tools/utils/index.tsx
Remove logic to extract mapping target, replace with url
Return url instead of target
Run new id mapping job
> 2021_05-update_status

- src/shared/components/layouts/ReleaseInfo.tsx
- src/shared/components/results/Results.tsx
- src/shared/components/results/__tests__/ResultsFacets.spec.tsx
- src/shared/hooks/usePagination.ts
- src/tools/state/getCheckJobStatus.ts
- src/uniprotkb/components/__mocks__/mockApi.ts
- src/uniprotkb/components/entry/EntryPublications.tsx
- src/uniprotkb/components/entry/__tests__/Entry.spec.tsx
- src/uniprotkb/components/entry/__tests__/EntryPublications.spec.tsx
- src/uniprotkb/types/responseTypes.ts
- src/uniref/components/entry/MembersSection.tsx
- src/uniref/types/responseTypes.ts
Update headers according to backend changes
Update headers according to backend changes
Update tests and mocks, tests still passing
> change expected headers from backend

- package.json
- src/app/components/home-page/__tests__/__snapshots__/HomePage.spec.tsx.snap
- src/shared/components/layouts/ReleaseInfo.tsx
- src/shared/components/layouts/UniProtHeader.tsx
- src/shared/components/layouts/__tests__/__snapshots__/UniProtFooter.spec.tsx.snap
- src/shared/components/layouts/styles/release-info.scss
- src/shared/components/layouts/styles/uniprot-header.scss
- src/shared/components/search/SearchContainer.tsx
- src/shared/components/search/__tests__/__snapshots__/SearchContainer.spec.tsx.snap
- yarn.lock
Update header according to new mockups
Use new main search component to display relevant links.
N/a
> 2021 06 header changes

- src/shared/components/results/ResultsButtons.tsx
Just ahead of SAB, makes things cleaner with the content we have
- Disable statistics button for now
- Add a dynamic title to the view mode switch to help the user understand what it does
> modify slightly the action bar content

- src/shared/components/results/ResultsData.tsx
- src/shared/utils/getIdKeyForNamespace.ts
- src/tools/config/urls.ts
- src/tools/id-mapping/components/IDMappingForm.tsx
- src/tools/id-mapping/components/results/IDMappingResult.tsx
- src/tools/state/getCheckJobStatus.ts
Fix a few issues with id mapping
- default to Table view mode
- use composite key for id mapping column
- improve "missing ids"
N/A
> 2021 05 idmapping fixes

- src/app/components/home-page/CoreData.tsx
- src/app/components/home-page/__tests__/__snapshots__/NonCritical.spec.tsx.snap
- src/shared/hooks/useNSQuery.ts
Backend asked us to optimise queries
- Use query instead of facet to get the SwissProt/TrEMBL * results from the tile
- Remove facets when not needed
> Update query for backend

- src/uniprotkb/components/entry/EntryPublications.tsx
- src/uniprotkb/config/database.ts
Missing annotation info from community annotation
https://www.ebi.ac.uk/panda/jira/browse/TRM-26093
Added to the info list. The example in the Jira covers most cases, but I couldn't find one with "disease", so will ask Cecilia to check once it's deployed.
No additional tests were added
> Add missing info

- src/proteomes/config/__tests__/__snapshots__/ProteomesColumnConfiguration.spec.tsx.snap
- src/shared/components/BasketStatus.tsx
- src/shared/components/action-buttons/AddToBasket.tsx
- src/shared/components/entry/styles/entry-title.scss
- src/shared/components/results/AccessionView.tsx
- src/shared/components/results/__tests__/__snapshots__/ResultsData.spec.tsx.snap
- src/shared/components/styles/basket-status.module.scss
- src/supporting-data/database/config/__tests__/__snapshots__/DatabaseColumnConfiguration.spec.tsx.snap
- src/supporting-data/locations/config/__tests__/__snapshots__/LocationsColumnConfiguration.spec.tsx.snap
- src/uniparc/components/entry/Entry.tsx
- src/uniparc/config/UniParcXRefsColumnConfiguration.tsx
- src/uniparc/config/__tests__/__snapshots__/UniParcColumnConfiguration.spec.tsx.snap
- src/uniprotkb/components/entry/Entry.tsx
- src/uniprotkb/components/entry/__tests__/__snapshots__/ComputationallyMappedSequences.spec.tsx.snap
- src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
- src/uniref/components/entry/Entry.tsx
- src/uniref/components/entry/MembersSection.tsx
- src/uniref/config/__tests__/__snapshots__/UniRefColumnConfiguration.spec.tsx.snap
Follow up of https://github.com/ebi-uniprot/uniprot-website/pull/393 implementing design and behaviour proposals
Change icon, size, and positionning.
Add logic to remove from basket on entry pages when already in the basket.
> follow first design proposals for basket status icon

- .gitlab-ci.yml
Travis informed us of when a PR would fail if merged. This PR tries to reproduce the same functionality.
1. Condition on `merge_request_event`
2. Checkout the target and merge in with a dummy commit message
3. If conflicts, bail
4. Else, test
If it works will copy this to franklin.
Also stopped replaced `buildkite/puppeteer` with `node:15` as we weren't using it.
N/A
> Merge and test on PRs.

- src/uniprotkb/config/UniProtKBColumnConfiguration.tsx
- src/uniprotkb/utils/__tests__/resultsUtils.spec.ts
- src/uniprotkb/utils/resultsUtils.ts
> proposal for a sort change

- src/uniprotkb/components/entry/FunctionSection.tsx
- src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
[Jira: resync function section comments with current site](https://www.ebi.ac.uk/panda/jira/browse/TRM-26461)
Reorder
Snapshot update
> 2021 11 function comments reorder

- package.json
- src/proteomes/components/entry/ComponentsButtons.tsx
- src/shared/components/action-buttons/CustomiseButton.tsx
- src/shared/components/results/ResultsButtons.tsx
- src/shared/components/results/TaxonomyFacet.tsx
- src/shared/components/search/SearchContainer.tsx
- src/tools/components/ResultButtons.tsx
- yarn.lock
Close the sliding panel when clicking on the button used to open it. https://www.ebi.ac.uk/panda/jira/browse/TRM-26450
Update franklin (pending)
Rewrite some of the logic to open/close sliding panels
Kept current tests
Draft, pending franklin update
> make sliding panel close when clicking on the button used to open

- package.json
- src/automatic-annotations/unirule/config/UniRuleColumnConfiguration.tsx
- src/automatic-annotations/unirule/config/__tests__/__snapshots__/UniRuleColumnConfiguration.spec.tsx.snap
- src/uniprotkb/components/protein-data-views/CSVView.tsx
Add predicted protein name column https://www.ebi.ac.uk/panda/jira/browse/TRM-26594
Use exact same approach as UniProtKB results page protein name column
> 2021 12 rule column predicted protein name

- src/automatic-annotations/arba/config/ARBAColumnConfiguration.tsx
- src/automatic-annotations/arba/config/__tests__/__snapshots__/ARBAColumnConfiguration.spec.tsx.snap
- src/automatic-annotations/shared/column-renderers/AnnotationCovered.tsx
- src/automatic-annotations/unirule/config/UniRuleColumnConfiguration.tsx
- src/automatic-annotations/unirule/config/__tests__/__snapshots__/UniRuleColumnConfiguration.spec.tsx.snap
Add annotation covered column to UniRule and ARBA https://www.ebi.ac.uk/panda/jira/browse/TRM-26592
Common renderer for both namespaces (see TaxonomicScope approach)
> 2021 12 rule column annotation covered

- package.json
- src/automatic-annotations/shared/column-renderers/AnnotationCovered.tsx
- src/automatic-annotations/shared/entry/ConditionsAnnotations.tsx
- src/shared/components/entry/TaxonomyView.tsx
- src/shared/components/error-component/ErrorBoundary.tsx
- src/shared/hooks/__tests__/useDataApi.spec.ts
- src/shared/hooks/useDataApi.ts
- src/shared/hooks/useStructuredData.ts
- src/shared/utils/__tests__/logging.spec.ts
- src/shared/utils/logging.ts
- src/tools/components/SequenceSearchLoader.tsx
- src/tools/peptide-search/components/results/PeptideSearchResult.tsx
- src/tools/state/getCheckJobStatus.ts
- src/uniprotkb/components/entry/EntryHistory.tsx
- src/uniprotkb/components/protein-data-views/__tests__/CatalyticActivityView.spec.tsx
- yarn.lock
Changes in logging module API, and changes in useDataAPI as to not report 404 that might correspond to "no data" but be valid
Updated/removed tests
> changes in logging module, and in useDataAPI

- src/automatic-annotations/arba/config/ARBAFacetConfiguration.tsx
- src/automatic-annotations/unirule/config/UniRuleFacetConfiguration.tsx
Update automatic annotations facets https://www.ebi.ac.uk/panda/jira/browse/TRM-26913
to test with the dev API, run `yarn run start --env API_PREFIX=https://wwwdev.ebi.ac.uk/uniprot/beta/api`
> update facets for automatic annotations

- src/uniprotkb/adapters/functionConverter.ts
- src/uniprotkb/adapters/slimming/GORibbonHandler.ts
- src/uniprotkb/adapters/slimming/__tests__/GoRibbonHandler.spec.ts
- src/uniprotkb/components/entry/FunctionSection.tsx
- src/uniprotkb/components/entry/GoRibbon.tsx
Pass subject props from entry data.
Update data adapter and pass through the props until it gets to `getSubjects`
Updated unit test
> 2021 15 slim sets: subject props

- src/uniprotkb/adapters/functionConverter.ts
- src/uniprotkb/adapters/slimming/GORibbonHandler.ts
- src/uniprotkb/components/entry/GoRibbon.tsx
- src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Change way to load data to avoid directly using axios, and to reuse the existing logic in the rest of the website.
Create a new hook to do the data loading of both endpoints
> 2021 15 slim sets data loading

- index.html
Make things more explicit about blocking extra google analytics stuff
> go crazy explicit about what data we want to discard

- src/uniprotkb/adapters/functionConverter.ts
- src/uniprotkb/components/entry/GoRibbon.tsx
- src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
- src/uniprotkb/components/protein-data-views/GOTermEvidenceTag.tsx
Add correct evidence ribbon colour based on evidence prefix
Re-use existing definition
N/A
> 2021_15-slim_sets--evidence

- src/uniprotkb/components/entry/FunctionSection.tsx
- src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap
- src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
- src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Add missing vmax annotation https://www.ebi.ac.uk/panda/jira/browse/TRM-26980
Add missing vmax annotation
Fix incorrect unit in data to use proper greek letter
Test by comparing the Kinetics sections in current and beta websites for P35503
> 2021 16 #26980 vmax

- src/app/config/urls.ts
- src/shared/components/action-buttons/ToolsButton.tsx
- src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap
- src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
- src/uniprotkb/components/protein-data-views/UniProtKBFeaturesView.tsx
- src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/FeaturesView.spec.tsx.snap
- src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
> 2021 16 subsequence links

- src/shared/components/entry/SequenceView.tsx
- src/shared/components/entry/__tests__/__snapshots__/SequenceView.spec.tsx.snap
- src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap
- src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
- src/uniprotkb/components/protein-data-views/CatalyticActivityView.tsx
- src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/CatalyticActivityView.spec.tsx.snap
- src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Some small visual improvements
- Use long number for sequence
- Separate EC number and the reaction direction with a line break
- Used a full stop after the reaction direction
Snapshots updated
> Small visual changes

- package.json
- src/query-builder/components/QueryBuilder.tsx
- src/shared/components/layouts/ReleaseInfo.tsx
- src/shared/components/results/Results.tsx
- src/shared/components/results/ResultsDataHeader.tsx
- src/shared/components/results/SearchSuggestions.tsx
- src/shared/components/results/__tests__/SearchSuggestions.spec.tsx
- src/shared/components/results/__tests__/__snapshots__/SearchSuggestions.spec.tsx.snap
- yarn.lock
Filter suggestions for search refinement https://www.ebi.ac.uk/panda/jira/browse/TRM-26349
- Add a network query to get suggestions (only if we think we might get suggestions)
- Add a network query to enrich the field values with proper labels (`lit_author` => `Author`)
- Display the list of suggestions with links next to the result count
- Try to fit as much links as possible in one line, then add a `[...]`
- If everything fits, not `[...]`
- If even just 1 link doesn't fit, just use an extra line and shove as much links as possible in that line
- Only does that on render, not on window resize
New unit tests and 1 snapshot
Additionally, test in the browser for the link fitting algorithm
> Suggest terms

- src/contact/adapters/__tests__/contactFormAdapter.spec.ts
- src/contact/adapters/contactFormAdapter.ts
- src/contact/components/ContactForm.tsx
> Parse form and submit

- src/contact/components/ContactForm.tsx
- src/uniprotkb/components/entry/Entry.tsx
- src/uniprotkb/components/entry/__tests__/__snapshots__/Entry.spec.tsx.snap
Display entry type and accession in subject if update requested.
already discussed
> 2022_01-update_entry

- src/contact/adapters/__tests__/__snapshots__/contactFormAdapter.spec.ts.snap
- src/contact/adapters/__tests__/contactFormAdapter.spec.ts
- src/contact/adapters/contactFormAdapter.ts
- src/contact/components/ContactForm.tsx
- src/contact/components/__tests__/ContactForm.spec.tsx
- src/contact/components/__tests__/__snapshots__/ContactForm.spec.tsx.snap
- src/shared/config/apiUrls.ts
- src/shared/config/testingApiUrls.ts
Retrieve token
Add success behaviour
Start adding tests
Moved all the logic in a custom hook in order to test form and logic independently
Started adding some tests for the form
- [] I have checked that linting checks pass and type safety is respected
> 2022 01 contact page token + success message + tests

- src/help/components/contextual/ContextualHelp.tsx
- src/help/components/contextual/ContextualHelpContainer.tsx
- src/help/components/entry/Entry.tsx
- src/proteomes/components/entry/Overview.tsx
- src/proteomes/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
Add proteomes links. Some contain a link to a subsection of a help article.
Split the :accession by '#'. If there is a hash, scroll to it once the article is loaded.
> 2022_02-contextual_hash

- package.json
- src/help/config/UniProtkbColumnHeaders.tsx
- src/proteomes/components/BuscoAbbr.tsx
- src/proteomes/components/results/__tests__/__snapshots__/ProteomesCard.spec.tsx.snap
- src/proteomes/config/ProteomesColumnConfiguration.tsx
- src/shared/components/results/__tests__/__snapshots__/ResultsData.spec.tsx.snap
- src/shared/hooks/useColumns.tsx
- src/shared/types/columnConfiguration.ts
- src/uniparc/config/UniParcColumnConfiguration.tsx
- src/uniprotkb/config/UniProtKBColumnConfiguration.tsx
- src/uniref/config/UniRefColumnConfiguration.tsx
- yarn.lock
Add tooltips for column headers
Create config file to host the definition. Wire in to the data-table component.
none
> 2022 02 colheaders

- src/shared/components/layouts/styles/side-bar-layout.scss
- src/shared/components/results/styles/results-data.scss
Reverts ebi-uniprot/uniprot-website#540
> Revert "2022 02 layout fix intent"

- src/shared/components/results/ResultsDataHeader.tsx
- src/tools/peptide-search/components/results/PeptideSearchResult.tsx
- src/tools/peptide-search/components/results/__tests__/PeptideSearchResult.spec.tsx
- src/tools/peptide-search/components/results/__tests__/__snapshots__/PeptideSearchResult.spec.tsx.snap
- List name of tool at start of title
- Remove peptide search string query from title
Updated unit test and snapshots
> 2022 04 tools adv search title

- src/shared/components/download/Download.tsx
- src/shared/contexts/IDMappingDetails.tsx
- src/tools/id-mapping/components/results/IDMappingResultTable.tsx
ID mapping download wasn't using the stream endpoint
In the Download component determine if it's mapping results and if so also check if it's namespaced and create the appropriate url.
manual
> Id mapping stream

- src/shared/components/action-buttons/AddToBasket.tsx
- src/shared/components/action-buttons/Align.tsx
- src/shared/components/action-buttons/Blast.tsx
- src/shared/components/action-buttons/MapID.tsx
- src/shared/config/__tests__/apiUrls.spec.ts
- src/shared/config/apiUrls.ts
- src/shared/utils/getIdKeyForNamespace.ts
Fix selection in ID mapping results
Clean-up the "from" in the row ID wherever the selection is used.
Not a big fan of the approach
Added 1 new test set
> fix selection

- src/shared/config/apiUrls.ts
- src/tools/blast/components/results/BlastResult.tsx
- src/tools/blast/components/results/BlastResultLocalFacets.tsx
- src/tools/blast/components/results/BlastResultSidebar.tsx
- src/tools/blast/components/results/BlastResultTable.tsx
- src/tools/config/urls.ts
Update codebase to use new way of filtering in accessions endpoints (all in query, no `facetFilters` anymore)
> 2022 05 backend changes

- src/uniprotkb/components/entry/__tests__/__mocks__/clusterMappingData.ts
- src/uniprotkb/components/entry/similar-proteins/SimilarProteins.tsx
Using more objects for creating the cluster mappings.
> Use objects in mapping.

- src/app/components/home-page/NeedHelp.tsx
- src/app/config/urls.ts
- src/contact/components/ContactForm.tsx
- src/contact/components/ContactLink.tsx
- src/contact/components/__tests__/__snapshots__/ContactForm.spec.tsx.snap
- src/help/components/contextual/Shortcuts.tsx
- src/shared/components/error-pages/NoResultsPage.tsx
- src/shared/components/error-pages/__tests__/__snapshots__/NoResultsPage.spec.tsx.snap
- src/shared/components/results/DidYouMean.tsx
- src/shared/components/results/Results.tsx
- src/shared/components/results/__tests__/DidYouMean.spec.tsx
- src/shared/components/results/styles/did-you-mean.module.scss
- src/shared/components/results/styles/results.module.scss
- src/uniprotkb/components/entry/Entry.tsx
Create a `DidYouMean` component
- Created `DidYouMean` which is provided to `NoResultsPage` via a new optional `message` prop.
- Left align of content agreed with @MarijaLuu
- Fetch other namespace suggestions with `fetchData`
- When loading of other namespace suggestions takes longer than 3s display "Sorry no results". 
- Created `searchLocations` to go from `Namespace` to the search location.
Created unit test
> 2022 05 did you mean initial component

- src/shared/components/search/SearchContainer.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-27749 -> trim the input search
https://www.ebi.ac.uk/panda/jira/browse/TRM-27722 -> replaceAll special keywords to uppercase
Manual checks
> process the search string as passed by the user to do common useful cleanup

- .gitlab-ci.yml
- package.json
- src/app/components/App.tsx
- src/app/components/DeploymentWarning.tsx
- src/app/components/styles/deployment-warning.module.scss
- src/types/webpack-define-plugin.d.ts
- webpack.config.js
Note that if this is merged it will cause beta to have the dev banner.
1. Allow us to deploy only prod or development if needed
2. Show a dismissible dev banner for non-www.uniprot.org deployments
1. Create some `if-elif-else` logic in gitlabci.
2. Create a `DeploymentWarning` component.
None
> Deploy warning

- package.json
- src/shared/components/entry/EntryTypeIcon.tsx
- yarn.lock
Icons for Redundant and Excluded proteomes added related to https://www.ebi.ac.uk/panda/jira/browse/TRM-27576
Exported from Franklin sites
-
> Proteome icons

- index.html
- src/app/components/DeploymentWarning.tsx
To be merged a bit before the release
> reenable dev warning message + remove robot meta tag

- src/uniprotkb/utils/__tests__/xrefUtils.spec.ts
- src/uniprotkb/utils/xrefUtils.ts
https://www.ebi.ac.uk/panda/jira/browse/TRM-28131
Update ClinGen and GenCC to use HGNC ids to form url.
Create an exception in the formation of implicit xrefs to append the HGNC id.
Genetic Variation databases here:
http://localhost:8080/uniprotkb/A0A0C5B5G6/external-links
Updated
> Clingen gencc

- src/shared/components/download/DownloadAPIURL.tsx
- src/shared/components/download/__tests__/DownloadAPIURL.spec.tsx
The search/pagination URL is incorrect for id mapping results
https://www.ebi.ac.uk/panda/jira/browse/TRM-28162
Create function to transform stream URL to correct search URL
Unit tests
> Idmapping pagination url link fix

- src/uniprotkb/components/entry/EntryPublications.tsx
Merging the publication reference into one
https://www.ebi.ac.uk/panda/jira/browse/TRM-27958
Instead of having a InfoList per reference, all references are merged and passed.
> Merge publication references

- src/index.tsx
- src/service-worker/service-worker.ts
- webpack.config.js
start reactivating the service worker logic that we had on beta, but partially, and with data being kept in cache for less time
> start reactivating the service worker logic, partially

- src/uniprotkb/components/protein-data-views/FreeTextView.tsx
- src/uniprotkb/components/protein-data-views/SimilarityView.tsx
- src/uniprotkb/components/protein-data-views/__tests__/SimilarityView.spec.tsx
- src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/SimilarityView.spec.tsx.snap
- src/uniprotkb/utils/index.ts
Fix the wrong/missing links
Separate the logic from FreeTextView and make it an individual component and  add additional conditions.
SimilarityView.spec.tsx to test few edge cases
> 2022 12 Protein family string parsing 

- src/automatic-annotations/shared/entry/ConditionsAnnotations.tsx
- src/automatic-annotations/unirule/components/entry/Source.tsx
- src/shared/config/externalUrls.ts
- src/uniparc/config/__tests__/__snapshots__/UniParcColumnConfiguration.spec.tsx.snap
- src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
Update rule and signature links for HAMAP and Prosite in UniRule pages. (https://www.ebi.ac.uk/panda/jira/browse/TRM-28320)
Also, Pfam links are updated.
> 2022 13 url link update

- src/shared/hooks/usePaginatedAccessions.ts
- src/shared/hooks/usePagination.ts
- src/tools/peptide-search/components/PeptideSearchMatches.tsx
- src/tools/peptide-search/components/results/PeptideSearchResult.tsx
- src/tools/peptide-search/components/results/__tests__/__snapshots__/PeptideSearchResult.spec.tsx.snap
Fix error when there are more than 1000 matches for peptide search - https://www.ebi.ac.uk/panda/jira/browse/TRM-26970
Send batches of 1000 accessions and display the results.
> 2022 13 peptide search

- src/uniprotkb/adapters/__tests__/evidenceCodes.spec.ts
- src/uniprotkb/components/protein-data-views/GOTermEvidenceTag.tsx
- src/uniprotkb/components/protein-data-views/PtmExchangeEvidenceTag.tsx
- src/uniprotkb/components/protein-data-views/UniProtKBEvidenceTag.tsx
- src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/PtmExchangeEvidenceTag.spec.tsx.snap
- src/uniprotkb/config/evidenceCodes.ts
Some ECO codes are interpreted differently. 
https://www.ebi.ac.uk/panda/jira/browse/TRM-27017
(https://www.ebi.ac.uk/panda/jira/browse/TRM-26978?focusedCommentId=376847&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-376847
Our code has to be updated to be in line with the above conditions
Evidence's label is changed to a function from string, as it allows for conditional checks.
> Refactor evidence codes 

- src/app/components/home-page/LatestNews.tsx
- src/app/components/home-page/__tests__/__snapshots__/NonCritical.spec.tsx.snap
> Release 2022_05

- src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
- src/uniprotkb/components/entry/__tests__/__snapshots__/ProteinProcessingSection.spec.tsx.snap
- src/uniprotkb/components/protein-data-views/ProteinNamesView.tsx
- src/uniprotkb/components/protein-data-views/UniProtKBFeaturesView.tsx
- src/uniprotkb/components/protein-data-views/__tests__/ProteinNamesView.spec.tsx
- src/uniprotkb/components/protein-data-views/__tests__/__snapshots__/FeaturesView.spec.tsx.snap
- src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
- src/uniprotkb/utils/index.ts
Visual improvement on protein name section. JIRA - https://www.ebi.ac.uk/panda/jira/browse/TRM-28855
Link the name to the corresponding row in PTM table and text formatting for 'Alternative names' from bold to italic to make it subtle.
> 2022 16 protein names

- src/uniprotkb/adapters/__tests__/functionConverter.spec.ts
- src/uniprotkb/adapters/functionConverter.ts
- src/uniprotkb/components/entry/FunctionSection.tsx
- src/uniprotkb/components/entry/KineticsTableView.tsx
- src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
- src/uniprotkb/components/entry/styles/kinetics-table.module.scss
- src/uniprotkb/config/UniProtKBColumnConfiguration.tsx
- src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
Show isoform info for kinetics data. JIRA - https://www.ebi.ac.uk/panda/jira/browse/TRM-28976
Separate table for isoform if present.
Changes done in entry page and in search results page (where they are listed)
Example query: *PDE4A
> Include isoform details in Kinetics section

- src/uniprotkb/components/entry/KineticsTableView.tsx
Dealing with scientific notation if present
https://www.ebi.ac.uk/panda/jira/browse/TRM-29055
Having a separate RegEx for kinetics as discussed 
> Parsing issue in kinetics

- src/uniprotkb/config/UniProtKBColumnConfiguration.tsx
[Publication ID column inconsistencies](https://www.ebi.ac.uk/panda/jira/browse/TRM-29030)
- Update column name
- Use regexp to filter out non-pubmed IDs
None
> Update PubMed ID column name; only show PMIDs.

- src/shared/components/results/AdvancedSearchSuggestion.tsx
- src/shared/components/results/ExactFieldSuggestion.tsx
- src/shared/components/results/OrganismSuggestion.tsx
- src/shared/components/results/ProteomeSuggestion.tsx
- src/shared/components/results/ResultsFacets.tsx
- src/shared/components/results/SearchSuggestions.tsx
- src/shared/components/results/TaxonomyLevelsSuggestion.tsx
- src/shared/components/results/__tests__/SearchSuggestions.spec.tsx
- src/shared/components/results/__tests__/__snapshots__/SearchSuggestions.spec.tsx.snap
- src/shared/config/apiUrls.ts
Add search suggestions for search terms that has exact macthes like Gene and E.C. number.
The above as part of this JIRA - https://www.ebi.ac.uk/panda/jira/browse/TRM-29051
Parse and modify the clause and pass the query int he same original order
> Search suggestions

- src/shared/components/entry/styles/entry-page.scss
- src/shared/components/layouts/SideBarLayout.tsx
- src/shared/components/layouts/styles/sidebar-layout.module.scss
Remove sidebar for entry pages for small screens
Added media query and checked the wider-tab-content to be active only when it is *not* small. 
> Remove sidebar on mobile view

- package.json
- src/basket/BasketMiniView.tsx
- src/help/components/contextual/ContextualHelp.tsx
- src/help/components/contextual/ContextualHelpContainer.tsx
- src/proteomes/components/entry/ComponentsButtons.tsx
- src/shared/components/action-buttons/CustomiseButton.tsx
- src/shared/components/download/Download.tsx
- src/shared/components/entry/SequenceView.tsx
- src/shared/components/layouts/SecondaryItems.tsx
- src/shared/components/results/ResultsButtons.tsx
- src/shared/components/search/SearchContainer.tsx
- src/shared/utils/gtagEvents.ts
- src/tools/async-download/components/AsyncDownloadForm.tsx
- src/tools/dashboard/components/Dashboard.tsx
- yarn.lock
Add remaining ga4 events as described in [confluence document](https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?spaceKey=UniProt&title=Google+Analytics+4) [Jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-29187)
None
> More ga4 events

- src/tools/align/state/alignFormReducer.ts
- src/tools/blast/state/blastFormReducer.ts
- src/tools/dashboard/components/Row.tsx
- src/tools/id-mapping/state/idMappingFormReducer.ts
- src/tools/peptide-search/state/peptideSearchFormReducer.ts
Populate job name on job resubmission (for all of the tools)
Fix peptide search resubmit bug. 
Pass the job title to history state along with the form parameters
> Job resubmit issues

- src/app/components/home-page/LatestNews.tsx
- src/app/components/home-page/__tests__/__snapshots__/NonCritical.spec.tsx.snap
- src/shared/components/entry/TaxonomyView.tsx
- src/supporting-data/taxonomy/__mocks__/taxonomyModelData.ts
- src/uniprotkb/utils/__tests__/__mocks__/databaseInfo.ts
- src/uniprotkb/utils/__tests__/__snapshots__/database.spec.ts.snap
> Release 2023_03

- src/shared/hooks/usePagination.ts
- src/shared/types/results.ts
- src/tools/id-mapping/components/results/IDMappingResultTable.tsx
- src/tools/id-mapping/components/results/__mocks__/SimpleMapping.ts
- src/tools/id-mapping/components/results/__tests__/IDMappingResult.spec.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-29997
Example IDs: P12345,P05067,A0A852YP84,A0A008APQ8
Added a test
> Show deleted entries count in ID mapping results

- src/uniprotkb/components/protein-data-views/CSVView.tsx
- src/uniprotkb/components/protein-data-views/__tests__/CSVView.spec.tsx
- src/uniprotkb/config/UniProtKBColumnConfiguration.tsx
- src/uniprotkb/config/__tests__/__snapshots__/UniProtKBColumnConfiguration.spec.tsx.snap
https://www.ebi.ac.uk/panda/jira/browse/TRM-29291
Added a property in the CSV component to show additional information within the ellipsis reveal
Added a test
> Show protein full name including the 'contains' part

- src/proteomes/components/entry/ComponentsButtons.tsx
- src/proteomes/components/entry/ComponentsDownload.tsx
- src/proteomes/components/entry/__tests__/ComponentsDownload.spec.tsx
- src/shared/components/download/styles/download.module.scss
https://www.ebi.ac.uk/panda/jira/browse/TRM-30140
The reviewed filter is added for all proteomes, as the isoforms logic is now separate, along with the other things mentioned in the JIRA
Updated test
> Proteomes download panel change

- src/shared/components/action-buttons/Blast.tsx
- src/shared/components/entry/SequenceView.tsx
- src/shared/components/entry/__tests__/__snapshots__/SequenceView.spec.tsx.snap
- src/tools/adapters/parameters.ts
- src/tools/blast/components/BlastForm.tsx
- src/tools/blast/components/__tests__/__snapshots__/BlastForm.spec.tsx.snap
- src/tools/state/getSubmitJob.ts
- src/tools/state/toolsActions.ts
- src/tools/state/toolsReducers.ts
- src/tools/types/toolsJob.ts
- src/uniprotkb/components/entry/ComputationallyMappedSequences.tsx
- src/uniprotkb/components/entry/__tests__/__snapshots__/ComputationallyMappedSequences.spec.tsx.snap
- src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
Suggested changes to BLAST. [TRM-30314](https://www.ebi.ac.uk/panda/jira/browse/TRM-30314)
New field in Job type. Changes in the hardcoded values.
> implement suggested BLAST changes

- src/shared/components/download/downloadUtils.ts
- src/tools/dashboard/components/styles/Dashboard.scss
- src/tools/state/getSubmitJob.ts
- src/tools/types/toolsJob.ts
https://www.ebi.ac.uk/panda/jira/browse/TRM-29906
Job submitted for testing - https://wwwdev.ebi.ac.uk/uniprot/api/uniref/download/details/9336050bc74a9b4b5a07b57b452acdf07395d063
> Uniref async download

- src/uniprotkb/adapters/uniProtkbConverter.ts
- src/uniprotkb/components/entry/NamesAndTaxonomySection.tsx
- src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
- src/uniprotkb/config/UniProtEntryConfig.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-27921
There are few edge cases where the evidences are not parsed. More info [here](https://www.ebi.ac.uk/panda/jira/browse/TRM-30548). It is taken from references and mapped in our side
> Include Organelle info in Names and taxonomy section

- src/uniprotkb/components/entry/KineticsTableView.tsx
- src/uniprotkb/components/entry/__tests__/KineticsTableView.spec.tsx
- src/uniprotkb/components/entry/__tests__/__mocks__/kineticsData.ts
Fix [text truncated in Kinetics table](https://www.ebi.ac.uk/panda/jira/browse/TRM-30466)
- Look up complicated regexp on stackoverflow which captures nested parentheses up to a depth of 3
- In the process of understanding the code moved a few things around and changed a few variable names
Added a unit test
> Nested parentheses substrate

- src/shared/components/entry/SequenceView.tsx
- src/uniprotkb/components/entry/__tests__/__snapshots__/EntryMain.spec.tsx.snap
https://www.ebi.ac.uk/panda/jira/browse/TRM-27769
Include evidence to synonyms in sequence and isoform section
> Sequence section

- src/tools/align/components/AlignForm.tsx
- src/tools/align/components/results/AlignResult.tsx
- src/tools/blast/components/BlastForm.tsx
- src/tools/blast/components/__tests__/__snapshots__/BlastForm.spec.tsx.snap
- src/tools/blast/components/results/BlastResult.tsx
- src/tools/components/DowntimeWarning.tsx
- src/tools/dashboard/components/Dashboard.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-30597
> Downtime announcement

- src/app/components/App.tsx
- src/app/components/home-page/NeedHelp.tsx
- src/app/components/home-page/training.structured.ts
- src/app/config/description.ts
- src/app/config/socialUrls.ts
- src/shared/components/layouts/Contact.tsx
- src/shared/components/layouts/UniProtHeader.tsx
[Fix schema issues and add more organization attributes.](https://www.ebi.ac.uk/panda/jira/browse/TRM-30601)
- Fix course instance by adding the properties that google requires
- Create some config files: `description` and `socialUrls`
- Create `isCourseOnline` and `isCourseOnsite` util fns
Copied `chrome > devtools > Elements > <html>` element and pasted into https://search.google.com/test/rich-results
> Schema updates

- src/shared/components/download/Download.tsx
- src/shared/components/download/DownloadAPIURL.tsx
- src/shared/components/download/__tests__/downloadUtils.spec.ts
- src/shared/components/download/downloadUtils.ts
- src/shared/config/__tests__/ftpUrls.spec.ts
- src/shared/config/ftpUrls.ts
[Suggest FTP for more search results downloads](https://www.ebi.ac.uk/panda/jira/browse/TRM-30641)
- Generalize existing logic by adding the dimension of namespace
- Add exceptions for uniparc
- Update download panel rendering to accommodate multiple files.
- Removed `src/shared/components/download/DownloadAPIURL.tsx` code which was an accidental duplicate
Added unit tests
> More ftp suggestions

- src/uniprotkb/components/protein-data-views/ProteomesView.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-27510
> Merge the data by proteome ID

- src/tools/components/SequenceSearchLoader.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-26640
> Truncate the error message shown in tools submission page

- src/tools/dashboard/components/Row.tsx
- src/tools/dashboard/components/styles/Dashboard.scss
https://www.ebi.ac.uk/panda/jira/browse/TRM-29110
Pass the error and job details as form values via the Link.
Pass job ID if available or else pass input parameters in the message. Since input params can be queried with the Job ID, this seemed to be better than passing inout all the time.
> Contact link for failed jobs

- src/shared/utils/gtagEvents.ts
- src/tools/align/components/AlignForm.tsx
- src/tools/async-download/components/AsyncDownloadForm.tsx
- src/tools/blast/components/BlastForm.tsx
- src/tools/id-mapping/components/IDMappingForm.tsx
- src/tools/peptide-search/components/PeptideSearchForm.tsx
https://www.ebi.ac.uk/panda/jira/browse/TRM-31093
Added a new tag and passing the relevant parameters if necessary
> GA4 tracking for job submission

- package.json
- src/uniprotkb/components/entry/Entry.tsx
- src/uniprotkb/components/entry/tabs/History.tsx
- src/uniprotkb/components/entry/tabs/__tests__/History.spec.ts
- src/uniprotkb/components/entry/tabs/styles/history.module.scss
[Quick links to navigate nearby history diffs](https://www.ebi.ac.uk/panda/jira/browse/TRM-31208)
- Created test cases then implemented function `getOtherDiffs`.
- Passed last version from top Entry component.
Wrote unit tests but still needed to drop the coverage.
> Unisave quick links

- src/uniprotkb/components/entry/InteractionSection.tsx
- src/uniprotkb/components/entry/__tests__/InteractionSection.spec.tsx
- src/uniprotkb/components/entry/__tests__/__snapshots__/InteractionSection.spec.tsx.snap
- src/uniprotkb/components/entry/styles/interaction-section.module.scss
- src/uniprotkb/components/protein-data-views/ComplexViewer.tsx
- Remove flex so complex and dropdown on separate lines.
- Show complex name with id.
> Show complex name

- src/uniprotkb/components/statistics/AbstractSectionTable.tsx
- src/uniprotkb/components/statistics/FrequencyTable.tsx
- src/uniprotkb/components/statistics/StatisticsPage.tsx
- src/uniprotkb/components/statistics/StatsTable.tsx
- src/uniprotkb/components/statistics/UniProtKBStatsTable.tsx
- src/uniprotkb/components/statistics/UniProtKBStatsTabs.tsx
- src/uniprotkb/components/statistics/UniqueReferencesTable.tsx
- src/uniprotkb/components/statistics/utils.ts
- src/uniprotkb/config/apiUrls/statistics.ts
https://www.ebi.ac.uk/panda/jira/browse/TRM-30436
Pass the new data instead of reviewed and unreviewed sum
> Use the new endpoint for combined UniProtKB stats

- src/uniprotkb/components/entry/InteractionSection.tsx
- src/uniprotkb/components/entry/__tests__/__snapshots__/InteractionSection.spec.tsx.snap
- src/uniprotkb/components/entry/styles/interaction-section.module.scss
https://www.ebi.ac.uk/panda/jira/browse/TRM-32113
> Add a subsection for complex viewer

- src/shared/components/results/DidYouMean.tsx
- src/shared/components/results/styles/did-you-mean.module.scss
- src/tools/blast/components/BlastForm.tsx
- src/tools/components/ChecksumSuggester.tsx
- src/tools/components/__tests__/ChecksumSuggester.spec.tsx
- src/tools/peptide-search/components/PeptideSearchForm.tsx
- [Suggest UniProtKB/UniParc entry when user searched for full sequence](https://www.ebi.ac.uk/panda/jira/browse/TRM-31822)
- [Change wording of did you mean component when user searched for sequence](https://www.ebi.ac.uk/panda/jira/browse/TRM-32188)
- Use `ChecksumSuggester` with some modifications.
- Tweak wording as requested
None
> Did you mean sequences

- src/tools/align/components/AlignForm.tsx
- src/tools/blast/components/BlastForm.tsx
- src/tools/blast/components/__tests__/__snapshots__/BlastForm.spec.tsx.snap
- src/tools/components/DowntimeWarning.tsx
- src/tools/dashboard/components/Dashboard.tsx
> add jdispatcher maintenance message

- src/help/components/contextual/SideButtons.tsx
- yarn.lock
Re-doing logic of moving hotjar feedback button to un-hide the scroll bar
moves the hotjar feedback button
> Feedback fallback removal

- src/app/components/home-page/NonCritical.tsx
- src/app/components/home-page/__tests__/__snapshots__/NonCritical.spec.tsx.snap
Draft PR, awaiting confirmation before publishing
> add EBI survey link to home page

- package.json
- src/uniprotkb/adapters/ptmExchangeFeaturesConverter.ts
- src/uniprotkb/components/protein-data-views/UniProtKBFeaturesView.tsx
- src/uniprotkb/utils/aa.ts
- yarn.lock
Show Ubiquitinylation and Acetylation modifications in proteomics section table. 
For feature viewer to work, this PR needs to be linked
https://github.com/ebi-webcomponents/protvista-uniprot/pull/81
> Show new PTM modifications

- src/jobs/id-mapping/components/results/IDMappingResultTable.tsx
Minor changes based on feedback from @tgttunstall.
> A few small ui tweaks.
